-- phpMyAdmin SQL Dump
-- version 4.1.14
-- http://www.phpmyadmin.net
--
-- Host: 127.0.0.1
-- Generation Time: 13 Jun 2015 pada 22.11
-- Versi Server: 5.6.17
-- PHP Version: 5.5.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `gpib`
--

-- --------------------------------------------------------

--
-- Struktur dari tabel `ci_sessions`
--

CREATE TABLE IF NOT EXISTS `ci_sessions` (
  `id` varchar(40) NOT NULL,
  `ip_address` varchar(45) NOT NULL,
  `timestamp` int(10) unsigned NOT NULL DEFAULT '0',
  `data` blob NOT NULL,
  PRIMARY KEY (`id`),
  KEY `ci_sessions_timestamp` (`timestamp`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- --------------------------------------------------------

--
-- Struktur dari tabel `tbl_berita`
--

CREATE TABLE IF NOT EXISTS `tbl_berita` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `cat_id` int(11) NOT NULL,
  `title` varchar(255) NOT NULL,
  `slug` varchar(255) NOT NULL,
  `desk` text NOT NULL,
  `file` varchar(255) NOT NULL,
  `author` int(11) NOT NULL,
  `update_by` int(11) NOT NULL,
  `create_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `update_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=21 ;

--
-- Dumping data untuk tabel `tbl_berita`
--

INSERT INTO `tbl_berita` (`id`, `cat_id`, `title`, `slug`, `desk`, `file`, `author`, `update_by`, `create_at`, `update_at`) VALUES
(3, 1, 'There is no one who loves pain itself', 'there-is-no-one-who-loves-pain-itself', '<p><strong>Lorem Ipsum</strong>&nbsp;is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry&#39;s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum</p>\r\n', '', 1, 0, '2015-06-07 22:29:54', '2015-06-08 03:29:54'),
(4, 9, 'Query Builder Class', 'query-builder-class', '<p>CodeIgniter gives you access to a Query Builder class. This pattern allows information to be retrieved, inserted, and updated in your database with minimal scripting. In some cases only one or two lines of code are necessary to perform a database action. CodeIgniter does not require that each database table be its own class file. It instead provides a more simplified interface.</p>\r\n\r\n<p>Beyond simplicity, a major benefit to using the Query Builder features is that it allows you to create database independent applications, since the query syntax is generated by each database adapter. It also allows for safer queries, since the values are escaped automatically by the system.</p>\r\n', '', 1, 0, '2015-06-08 03:27:43', '2015-06-08 08:27:43'),
(5, 11, 'Pembukaan Bulan Pelkes (dulu disebut Pekabaran Injil)', 'pembukaan-bulan-pelkes-dulu-disebut-pekabaran-injil', '<p>Pada awalnya istilah Pekabaran Injil (PI) dianggap netral, artinya tidak menimbulkan salah interpretasi dalam hubungan antar umat beragama di Indonesia. Namun, sejak tahun 70-an. Istilah PI mulai menimbulkan rasa curiga dan apriori dari pihak umat Muslim terhadap praktek dan kegiatan misi Kristiani di Indonesia. Kemudian, istilah PI dikaitkan dengan usaha Kristenisasi atau memaksa umat lain untuk menjadi Kristen. Umat Kristen dituduh menyebarkan agama dengan cara paksa atau membujuk dengan memberikan bantuan agar orang yang dibantu beralih dari agamanya yang semula menjadi Kristen.</p>\r\n\r\n<p>Tanpa bermaksud untuk menghilangkan istilah PI yang sudah baku digunakan gereja-gereja di Indonesia. GPIB menggunakan dan mempopulerkan Istilah Pelayanan dan Kesaksian (Pelkes). Pelkes merupakan 2 aspek dari tridharma gereja (persekutuan, pelayanan) dan kesaksian, sekaligus pengejawantahan maksud istilah PI tersebut.</p>\r\n\r\n<p>Dalam kembara perjalanan Pelkes tersebut, kasih Tuhan selalu dinyatakan. Menapaki hari-hari pemberian Tuhan dengan keyakinan penuh bahwa Ia selalu beserta. Bertumbuh, berkembang dan berproses ditengah jemaat Tuhan, merupakan berkat terindah. Kini dan disini, seorang hamba dibentuk untuk melayani dengan ketulusan, kejujuran dan kerendahan hati. Sejenak menoleh kebelakang untuk kembali menatap kedepan dan menjalani pelayanan ditempat yang baru hanya karena pertolongan Tuhan. Sungguh, semua hanya karena pertolongan Tuhan...</p>\r\n', 'Pendeta Ny. Maria Y. Silahooij,S.Th,M.Pd.K', 1, 0, '2015-06-11 23:47:35', '2015-06-12 04:47:35'),
(6, 14, 'Memaknai Peristiwa Pentakosta', 'memaknai-peristiwa-pentakosta', '<p>&quot;Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.&quot;</p>\r\n', '', 3, 0, '2015-06-12 22:28:01', '2015-06-13 15:28:01'),
(7, 4, 'Memaknai Peristiwa Pentakosta', 'memaknai-peristiwa-pentakosta', '<p>&quot;Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.&quot;</p>\r\n', '', 3, 0, '2015-06-12 22:36:59', '2015-06-13 15:36:59'),
(8, 4, 'Barangsiapa Takut ia Tidak Sempurna', 'barangsiapa-takut-ia-tidak-sempurna', '<p>&quot;Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.&quot;</p>\r\n', '', 3, 0, '2015-06-12 22:37:29', '2015-06-13 15:37:29'),
(9, 6, 'Selamat Berbahagia Irian Simanjuntak & Steven Chen', 'selamat-berbahagia-irian-simanjuntak-steven-chen', '<p>&quot;Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.&quot;</p>\r\n', '', 3, 0, '2015-06-12 23:10:03', '2015-06-13 16:10:03'),
(10, 6, 'Turut Berbahagia Atas Menikahnya Sdri Amanda Sari', 'turut-berbahagia-atas-menikahnya-sdri-amanda-sari', '<p>&quot;Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.&quot;</p>\r\n', '', 3, 0, '2015-06-12 23:10:41', '2015-06-13 16:10:41'),
(11, 8, 'Dibutuhkan Tenaga Mechanical Engineering', 'dibutuhkan-tenaga-mechanical-engineering', '<p>&quot;Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.&quot;</p>\r\n', '', 3, 0, '2015-06-12 23:18:44', '2015-06-13 16:18:44'),
(12, 8, 'Dibutuhkan Tenaga Pengajar Pada Sekolah Kristen Budi Murni', 'dibutuhkan-tenaga-pengajar-pada-sekolah-kristen-budi-murni', '<p>&quot;Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.&quot;</p>\r\n', '', 3, 0, '2015-06-12 23:19:19', '2015-06-13 16:19:19'),
(13, 7, 'Mohon Didoakan Keluarga Bpk Sihite', 'mohon-didoakan-keluarga-bpk-sihite', '<p>&quot;Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.&quot;</p>\r\n', '', 3, 0, '2015-06-12 23:26:14', '2015-06-13 16:26:14'),
(14, 7, 'Terbaring Sakit Sdri Joelina Marisa Simatupang', 'terbaring-sakit-sdri-joelina-marisa-simatupang', '<p>&quot;Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.&quot;</p>\\r\\n', '', 3, 3, '2015-06-12 23:27:06', '2015-06-13 16:27:24'),
(15, 15, 'Pelantikan Pengurus Muda-Mudi', 'pelantikan-pengurus-muda-mudi', '<p>&quot;Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.&quot;</p>\r\n', '', 3, 0, '2015-06-12 23:45:27', '2015-06-13 16:45:27'),
(16, 15, 'Bakti Sosial', 'bakti-sosial', '<p>&quot;Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.&quot;</p>\r\n', '', 3, 0, '2015-06-12 23:52:51', '2015-06-13 16:52:51'),
(17, 16, 'Kunjungan Ke Panti Asuhan', 'kunjungan-ke-panti-asuhan', '<p>&quot;Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.&quot;</p>\r\n', '', 3, 0, '2015-06-12 23:54:16', '2015-06-13 16:54:16'),
(18, 12, 'Walking in the footsteps of faith', 'walking-in-the-footsteps-of-faith', '<p>&quot;Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.&quot;</p>\\r\\n\\r\\n<p>&nbsp;</p>\\r\\n\\r\\n<p>Sabda Bina Umat: Renungan SBU Pagi 2015<br />\\r\\n&nbsp;</p>\\r\\n\\r\\n<p>&nbsp;</p>\\r\\n', '', 3, 3, '2015-06-13 00:40:33', '2015-06-13 17:42:18'),
(19, 12, 'Terus Menerus Dibarui Roh Kudus', 'terus-menerus-dibarui-roh-kudus', '<p>&quot;Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.&quot;</p>\\r\\n\\r\\n<p>&nbsp;</p>\\r\\n\\r\\n<p>Sabda Bina Umat: Renungan SBU Pagi 2015</p>\\r\\n', '', 3, 3, '2015-06-13 00:41:20', '2015-06-13 17:42:26'),
(20, 12, 'Menyukacitakan Roh Kudus', 'menyukacitakan-roh-kudus', '<p>&quot;Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.&quot;</p>\\r\\n', '', 3, 3, '2015-06-13 00:41:39', '2015-06-13 17:58:57');

-- --------------------------------------------------------

--
-- Struktur dari tabel `tbl_category`
--

CREATE TABLE IF NOT EXISTS `tbl_category` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(255) NOT NULL,
  `slug` varchar(255) NOT NULL,
  `desk` text NOT NULL,
  `parent_id` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=18 ;

--
-- Dumping data untuk tabel `tbl_category`
--

INSERT INTO `tbl_category` (`id`, `title`, `slug`, `desk`, `parent_id`) VALUES
(1, 'Catatan dari Meja Pendeta', 'catatan-dari-meja-pendeta', 'Catatan dari Meja Pendeta', 0),
(3, 'Sejarah', 'sejarah', '', 1),
(4, 'Informasi Sekretariat', 'informasi-sekretariat', 'Informasi Sekretariat', 0),
(5, 'Berita GPIB Immanuel Pekanbaru', 'berita-gpib-immanuel-pekanbaru', 'Berita GPIB Immanuel Pekanbaru', 0),
(6, 'Pemberkatan Pernikahan', 'pemberkatan-pernikahan', 'Pemberkatan Pernikahan', 5),
(7, 'Jemaat Sakit', 'jemaat-sakit', 'Jemaat Sakit', 5),
(8, 'Lowongan Kerja', 'lowongan-kerja', 'Lowongan Kerja', 5),
(9, 'Materi / Download', 'materi-download', 'Materi / Download', 5),
(10, 'Berita Gereja dan Dunia', 'berita-gereja-dan-dunia', 'Berita Gereja dan Dunia', 0),
(11, 'SMS Dari Pendeta', 'sms-dari-pendeta', '', 0),
(12, 'Renungan SBU Pagi', 'renungan-sbu-pagi', '', 0),
(13, 'Renungan SBU Malam', 'renungan-sbu-malam', '', 0),
(14, 'Berita Majelis Sinode GPIB', 'berita-majelis-sinode-gpib', 'berita majelis sinode GPIB', 0),
(15, 'Event', 'event', 'event dan kegiatan penting lainnya', 0),
(16, 'Kegiatan Lainnya', 'kegiatan-lainnya', 'kegiatan penting lainnya', 0);

-- --------------------------------------------------------

--
-- Struktur dari tabel `tbl_jemaat`
--

CREATE TABLE IF NOT EXISTS `tbl_jemaat` (
  `id` varchar(18) NOT NULL DEFAULT '',
  `first_name` varchar(20) NOT NULL,
  `middle_name` varchar(17) DEFAULT NULL,
  `last_name` varchar(20) NOT NULL,
  `gender` enum('LK','PR') NOT NULL,
  `relation` varchar(3) NOT NULL,
  `pob` varchar(20) DEFAULT NULL,
  `dob` date NOT NULL DEFAULT '0000-00-00',
  `status_baptis` tinyint(1) NOT NULL,
  `tempat_baptis` varchar(20) DEFAULT NULL,
  `tanggal_baptis` date NOT NULL DEFAULT '0000-00-00',
  `status_sidi` tinyint(1) NOT NULL,
  `tempat_sidi` varchar(20) DEFAULT NULL,
  `tanggal_sidi` date NOT NULL DEFAULT '0000-00-00',
  `status_nikah` int(2) DEFAULT NULL,
  `tanggal_nikah` date NOT NULL DEFAULT '0000-00-00',
  `nikah_sipil` date NOT NULL DEFAULT '0000-00-00',
  `telp` varchar(15) DEFAULT NULL,
  `hp` varchar(15) DEFAULT NULL,
  `alamat` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data untuk tabel `tbl_jemaat`
--

INSERT INTO `tbl_jemaat` (`id`, `first_name`, `middle_name`, `last_name`, `gender`, `relation`, `pob`, `dob`, `status_baptis`, `tempat_baptis`, `tanggal_baptis`, `status_sidi`, `tempat_sidi`, `tanggal_sidi`, `status_nikah`, `tanggal_nikah`, `nikah_sipil`, `telp`, `hp`, `alamat`) VALUES
('04.10-01-0001-01', 'AKWILA ', 'REKKY PETRUS ', 'DAMANIK', 'LK', 'KK', 'PEKANBARU', '1982-03-23', 1, 'PEKANBARU', '0000-00-00', 1, 'PEKANBARU', '0000-00-00', 1, '2011-11-17', '2011-11-17', '0761-36171', '', 'JL. BUNGA HARUM NO. 4  SUKAJADI HARJOSARI'),
('04.10-01-0001-02', 'ROMAULI', '', '', 'PR', 'IS', 'PEKANBARU', '0000-00-00', 1, 'PEKANBARU', '0000-00-00', 1, 'PEKANBARU', '0000-00-00', 1, '2011-11-17', '2011-11-17', '', '', 'JL. BUNGA HARUM NO. 4  SUKAJADI HARJOSARI'),
('04.10-01-0001-031', 'KEREN ', 'PRISKILA', 'DAMANIK', 'PR', 'AN', 'PEKANBARU', '2012-12-29', 0, '_', '0000-00-00', 0, '_', '0000-00-00', 0, '0000-00-00', '0000-00-00', '', '', 'JL. BUNGA HARUM NO. 4  SUKAJADI HARJOSARI'),
('04.10-01-0002-01', 'ABEL ', 'ROLAND ', 'GULTOM', 'LK', 'KK', 'MEDAN', '1972-09-08', 1, 'MEDAN', '1974-03-02', 1, 'CIMAHI', '1988-10-04', 1, '1999-08-21', '0000-00-00', '0761-28123', '08127669916', 'JL. ABABIL NIO. 15A  SUKAJADI KAMPUNG MELAYU'),
('04.10-01-0002-02', 'YULYATI', 'CHRISTIAN', 'ARUAN', 'PR', 'IS', 'JAKARTA', '1971-07-31', 1, 'LAGUBOTI', '1977-12-18', 1, 'KERNOLONG', '1988-10-04', 1, '1999-08-21', '0000-00-00', '', '08127669915', 'JL. ABABIL NIO. 15A  SUKAJADI KAMPUNG MELAYU'),
('04.10-01-0002-031', 'MATTHEW P. C', 'NATHANEL', 'GULTOM', 'LK', 'AN', 'PEKANBARU', '2000-06-12', 1, 'KERNOLONG', '2005-10-07', 0, '', '0000-00-00', 0, '0000-00-00', '0000-00-00', '', '', 'JL. ABABIL NIO. 15A  SUKAJADI KAMPUNG MELAYU'),
('04.10-01-0002-032', 'DAVID', 'CLEO', 'GULTOM', 'LK', 'AN', 'PEKANBARU', '2003-01-29', 1, 'KERNOLONG', '2005-10-07', 0, '', '0000-00-00', 0, '0000-00-00', '0000-00-00', '', '', 'JL. ABABIL NIO. 15A  SUKAJADI KAMPUNG MELAYU'),
('04.10-01-0002-033', 'TIMOTHY', 'CLEYTUS', 'GULTOM', 'LK', 'AN', 'PEKANBARU', '2003-01-29', 1, 'KERNOLONG', '2005-10-07', 0, '', '0000-00-00', 0, '0000-00-00', '0000-00-00', '', '', 'JL. ABABIL NIO. 15A  SUKAJADI KAMPUNG MELAYU'),
('04.10-01-0003-01', 'AKTOR ', 'JUANG ', 'LAOWO', 'LK', 'KK', 'NIAS SELATAN', '1988-08-31', 1, 'BNKP P. TELLO', '1989-02-05', 1, 'BNKP P. TELLO', '0000-00-00', 0, '0000-00-00', '0000-00-00', '', '081392866010', 'JL. AHMAD DAHLAN NO. 125  SUKAJADI '),
('04.10-01-0003-06', 'GUSWITA', '', 'LAOWO', 'PR', 'KA', 'NIAS SELATAN', '1986-08-09', 1, 'BNKP P. TELLO', '0000-00-00', 1, 'BNKP P. TELLO', '0000-00-00', 0, '0000-00-00', '0000-00-00', '', '081392137588', 'JL. AHMAD DAHLAN NO. 125  SUKAJADI '),
('04.10-01-0003-08', 'VICTOR', '', 'LAOWO', 'LK', 'FA', 'NIAS SELATAN', '1985-05-27', 1, 'BNKP P. TELLO', '0000-00-00', 1, 'BNKP P. TELLO', '0000-00-00', 0, '0000-00-00', '0000-00-00', '', '081371221011', 'JL. AHMAD DAHLAN NO. 125  SUKAJADI '),
('04.10-01-0004-01', 'AMES ', 'RESMAN ', 'DAMANIK', 'LK', 'KK', 'P. SIANTAR', '1946-12-28', 1, 'PEMATANG RAYA', '0000-00-00', 1, 'PEMATANG RAYA', '0000-00-00', 1, '1971-02-08', '1971-02-08', '0761-36171', '', 'JL. BUNGA HARUM NO. 4  SUKAJADI HARJOSARI'),
('04.10-01-0004-02', 'NURLINA', '', 'SARAGIH', 'PR', 'IS', 'P. SIANTAR', '1950-12-20', 1, 'PEMATANG RAYA', '0000-00-00', 1, 'PEMATANG RAYA', '0000-00-00', 1, '1971-02-08', '1971-02-08', '', '', 'JL. BUNGA HARUM NO. 4  SUKAJADI HARJOSARI'),
('04.10-01-0005-01', 'ANDREW ', 'RIGGS WILSON ', 'DAMANIK', 'LK', 'KK', 'PEKANBARU', '1978-02-12', 1, 'PEKANBARU', '0000-00-00', 1, 'PEKANBARU', '0000-00-00', 1, '0000-00-00', '0000-00-00', '0761-36171', '', 'JL. BUNGA HARUM NO. 4  SUKAJADI HARJOSARI'),
('04.10-01-0005-02', 'RIO', 'MARLINA ', 'PANJAITAN', 'PR', 'IS', 'PEKANBARU', '0000-00-00', 1, 'PEKANBARU', '0000-00-00', 1, 'PEKANBARU', '0000-00-00', 1, '0000-00-00', '0000-00-00', '', '', 'JL. BUNGA HARUM NO. 4  SUKAJADI HARJOSARI'),
('04.10-01-0005-031', 'ANUGERAH', 'PASKAH', 'DAMANIK', 'LK', 'AN', 'PEKANBARU', '0000-00-00', 1, 'PEKANBARU', '0000-00-00', 0, '', '0000-00-00', 0, '0000-00-00', '0000-00-00', '', '', 'JL. BUNGA HARUM NO. 4  SUKAJADI HARJOSARI'),
('04.10-01-0006-01', 'APREDING ', '', 'TANDIRURA', 'LK', 'KK', 'TORAJA', '1972-11-28', 1, 'TORAJA', '0000-00-00', 1, 'RANTEPAO', '1991-04-21', 1, '1999-10-10', '2001-10-30', '', '081378876658', 'ASRAMA BRIMOB BLOK F NO. 3 SUKAJADI -KAMPUNG MELAYU'),
('04.10-01-0006-02', 'ERNY ', 'SOFICE TULLE', '', 'PR', 'IS', 'BAUCAU', '1980-05-02', 1, 'ATAMBUA', '1982-04-12', 1, 'KUPANG', '1998-04-05', 1, '1999-10-10', '2001-10-30', '', '', 'ASRAMA BRIMOB BLOK F NO. 3 SUKAJADI -KAMPUNG MELAYU'),
('04.10-01-0006-031', 'JERREMY . A', '', 'TANDIRURA', 'LK', 'AN', 'PEKANBARU', '2001-05-24', 1, 'KUPANG', '2002-12-26', 0, '', '0000-00-00', 0, '0000-00-00', '0000-00-00', '', '', 'ASRAMA BRIMOB BLOK F NO. 3 SUKAJADI -KAMPUNG MELAYU'),
('04.10-01-0006-032', 'SAHRANY C.F', '', 'TANDIRURA', 'PR', 'AN', 'KUPANG', '2005-02-27', 1, 'KUPANG', '2005-09-04', 0, '', '0000-00-00', 0, '0000-00-00', '0000-00-00', '', '', 'ASRAMA BRIMOB BLOK F NO. 3 SUKAJADI -KAMPUNG MELAYU'),
('04.10-01-0007-01', 'BUDHI ', 'PRASETYO ', 'KORENGKENG', 'LK', 'KK', 'PEKANBARU', '1973-10-11', 1, 'KALI LERET - PATI', '1973-12-25', 1, 'PEKANBARU', '1993-04-04', 1, '2004-09-17', '0000-00-00', '0761-46459', '085265714224', 'JL. DURIAN NO. 3  SUKAJADI JADIREJO'),
('04.10-01-0007-02', 'SEPTINA ', 'MARYANTI', 'SIMANJUNTAK', 'PR', 'IS', 'PEKANBARU', '1975-09-23', 1, 'PEKANBARU', '1976-05-09', 1, 'PEKANBARU', '1993-05-23', 1, '2004-09-17', '0000-00-00', '', '085363982759', 'JL. DURIAN NO. 3  SUKAJADI JADIREJO'),
('04.10-01-0008-01', 'DAVID ', 'YUNIKO ', 'SILITONGA', 'LK', 'KK', 'MEDAN', '1977-06-11', 1, 'MEDAN', '1978-05-28', 1, 'MEDAN', '1994-06-12', 1, '2008-08-09', '2008-08-08', '0761-41287', '08136122887', 'JL. KH AHMAD DAHLAN NO. 85B RUKO SUKAJADI KAMPUNG TENGAH'),
('04.10-01-0008-02', 'RETNO ', 'INDRAWATI', 'SINGGIH', 'PR', 'IS', 'TALUK KUANTAN', '1979-02-28', 1, 'PEKANBARU', '1991-03-24', 1, 'PEKANBARU', '1998-05-24', 1, '2008-08-09', '2008-08-08', '', '081371500097', 'JL. KH AHMAD DAHLAN NO. 85B RUKO SUKAJADI KAMPUNG TENGAH'),
('04.10-01-0010-01', 'DJOKO ', '', 'SETIABOEDI', 'LK', 'KK', 'KUDUS', '1955-09-02', 1, 'KUDUS', '0000-00-00', 1, 'KUDUS', '0000-00-00', 1, '1986-07-07', '0000-00-00', '', '', 'JL. DURIAN GG. PEPAYA I NO. 42A  PERUMAHAN SUKAJADI PULAU KARAM'),
('04.10-01-0010-02', 'YOHANDRES', '', 'LIDYA', 'PR', 'IS', 'BENGKALIS', '1965-09-12', 1, 'BENGKALIS', '0000-00-00', 1, 'BENGKALIS', '0000-00-00', 1, '1986-07-07', '0000-00-00', '', '', 'JL. DURIAN GG. PEPAYA I NO. 42A  PERUMAHAN SUKAJADI PULAU KARAM'),
('04.10-01-0010-031', 'JODEA ANGGER', 'MOSESSA', '', 'LK', 'AN', 'PEKANBARU', '1987-06-10', 1, 'PEKANBARU', '0000-00-00', 1, 'TEMBILAHAN', '0000-00-00', 0, '0000-00-00', '0000-00-00', '', '', 'JL. DURIAN GG. PEPAYA I NO. 42A  PERUMAHAN SUKAJADI PULAU KARAM'),
('04.10-01-0010-032', 'JOSUA GILANG', 'YOSE SOGHANA', '', 'LK', 'AN', 'TEMBILAHAN', '1993-04-26', 1, 'TEMBILAHAN', '0000-00-00', 0, '', '0000-00-00', 0, '0000-00-00', '0000-00-00', '', '', 'JL. DURIAN GG. PEPAYA I NO. 42A  PERUMAHAN SUKAJADI PULAU KARAM'),
('04.10-01-0010-033', 'JOARES LANGGENG', 'TEGARA', '', 'LK', 'AN', 'TEMBILAHAN', '1999-07-23', 1, 'TEMBILAHAN', '0000-00-00', 0, '', '0000-00-00', 0, '0000-00-00', '0000-00-00', '', '', 'JL. DURIAN GG. PEPAYA I NO. 42A  PERUMAHAN SUKAJADI PULAU KARAM'),
('04.10-01-0011-01', 'FIRMAN MARULI ', 'HAMONANGAN ', 'PANDIANGAN', 'LK', 'KK', 'SAMOSIR', '1953-09-13', 1, 'HKBP MARTOBA SIANTAR', '1953-12-28', 1, 'HKBP MARTOBA SIANTAR', '1968-12-22', 1, '1982-04-17', '0000-00-00', '0761-20097', '08127534518', 'JL. ANGKASA NO. 9  PAYUNG SEKAKI AIR HITAM'),
('04.10-01-0011-02', 'ANI', 'NOVITA', 'SURBAKTI', 'PR', 'IS', 'MAGELANG', '1959-09-04', 1, '', '0000-00-00', 1, '', '0000-00-00', 1, '1982-04-17', '0000-00-00', '', '081371306097', 'JL. ANGKASA NO. 9  PAYUNG SEKAKI AIR HITAM'),
('04.10-01-0011-031', 'BENNY DWI', 'PUTRA', 'PANDIANGAN', 'LK', 'AN', 'PEKANBARU', '1990-06-21', 1, 'PEKANBARU', '1990-12-26', 1, '', '0000-00-00', 0, '0000-00-00', '0000-00-00', '', '', 'JL. ANGKASA NO. 9  PAYUNG SEKAKI AIR HITAM'),
('04.10-01-0011-032', 'DEBOY CHRISTINA', 'NATALIA', 'PANDIANGAN', 'PR', 'AN', 'PEKANBARU', '1995-12-06', 1, '', '0000-00-00', 0, '', '0000-00-00', 0, '0000-00-00', '0000-00-00', '', '', 'JL. ANGKASA NO. 9  PAYUNG SEKAKI AIR HITAM'),
('04.10-01-0011-033', 'THOMAS PAREL', 'HERMAWAN', 'PANDIANGAN', 'LK', 'AN', 'PEKANBARU', '1983-02-09', 1, '', '0000-00-00', 1, 'PEKANBARU', '2002-03-24', 0, '0000-00-00', '0000-00-00', '', '', 'JL. ANGKASA NO. 9  PAYUNG SEKAKI AIR HITAM'),
('04.10-01-0012-01', 'FIRMAN ', '', 'MARPAUNG', 'LK', 'KK', 'BANDUNG', '1941-09-18', 1, 'PEKANBARU', '0000-00-00', 1, 'PEKANBARU', '0000-00-00', 1, '0000-00-00', '0000-00-00', '', '081365685200', 'JL. KUTILANG NO. 25  SUKAJADI KAMPUNG MELAYU'),
('04.10-01-0012-02', 'ROSMIATI', '', 'SIAHAAN', 'PR', 'IS', 'PALOPO, SULSEL', '1954-12-27', 1, 'PEKANBARU', '0000-00-00', 1, 'PEKANBARU', '0000-00-00', 1, '0000-00-00', '0000-00-00', '', '', 'JL. KUTILANG NO. 25  SUKAJADI KAMPUNG MELAYU'),
('04.10-01-0013-01', 'HENDRI ', '', 'LAHEBA', 'LK', 'KK', 'JAKARTA', '1959-11-11', 1, '', '0000-00-00', 1, 'SELAT PANJANG', '0000-00-00', 1, '1990-07-07', '1990-07-07', '0761-36043', '0811767381', 'JL. MELUR GG. AL-JIHAD NO. 9  SUKAJADI KEDUNG SARI'),
('04.10-01-0013-02', 'ITA ', 'AGUSTINI', 'SUKATIYO', 'PR', 'IS', 'MEDAN', '1966-08-20', 1, 'MEDAN', '0000-00-00', 1, 'PEKANBARU', '0000-00-00', 1, '1990-07-07', '1990-07-07', '', '', 'JL. MELUR GG. AL-JIHAD NO. 9  SUKAJADI KEDUNG SARI'),
('04.10-01-0013-031', 'TIMOTHY ', 'REY', 'LAHEBA', 'LK', 'AN', 'PEKANBARU', '1991-03-20', 1, 'PEKANBARU', '0000-00-00', 1, 'PEKANBARU', '0000-00-00', 0, '0000-00-00', '0000-00-00', '', '', 'JL. MELUR GG. AL-JIHAD NO. 9  SUKAJADI KEDUNG SARI'),
('04.10-01-0013-032', 'TEOFILUS', 'HANS', 'LAHEBA', 'LK', 'AN', 'PEKANBARU', '1992-04-14', 1, 'PEKANBARU', '0000-00-00', 1, 'PEKANBARU', '0000-00-00', 0, '0000-00-00', '0000-00-00', '', '', 'JL. MELUR GG. AL-JIHAD NO. 9  SUKAJADI KEDUNG SARI'),
('04.10-01-0014-01', 'HERRY ', 'RAMON ', 'PANJAITAN', 'LK', 'KK', 'PEKANBARU', '1969-11-30', 1, 'PEKANBARU', '0000-00-00', 1, 'PEKANBARU', '0000-00-00', 1, '1905-06-25', '0000-00-00', '0761-885530', '', 'JL. KH AHMAD DAHLAN GG. KELINCI NO. 46 SUKAJADI HARJOSARI'),
('04.10-01-0014-02', 'CAROLINA', '', 'SIMAMORA', 'PR', 'IS', 'PEKANBARU', '1970-09-29', 1, 'PEKANBARU', '0000-00-00', 1, 'PEKANBARU', '0000-00-00', 1, '1905-06-25', '0000-00-00', '', '', 'JL. KH AHMAD DAHLAN GG. KELINCI NO. 46 SUKAJADI HARJOSARI'),
('04.10-01-0014-031', 'MANOAH', 'SOALOAN', 'PANJAITAN', 'LK', 'AN', 'PEKANBARU', '2003-10-29', 0, '', '0000-00-00', 0, '', '0000-00-00', 0, '0000-00-00', '0000-00-00', '', '', 'JL. KH AHMAD DAHLAN GG. KELINCI NO. 46 SUKAJADI HARJOSARI'),
('04.10-01-0014-032', 'DOMININGUS', 'NATALIA', 'PANJAITAN', 'LK', 'AN', 'PEKANBARU', '2008-02-09', 0, '', '0000-00-00', 0, '', '0000-00-00', 0, '0000-00-00', '0000-00-00', '', '', 'JL. KH AHMAD DAHLAN GG. KELINCI NO. 46 SUKAJADI HARJOSARI'),
('04.10-01-0014-033', 'VINCENT', '', 'PANJAITAN', 'LK', 'AN', 'PEKANBARU', '2009-11-22', 0, '', '0000-00-00', 0, '', '0000-00-00', 0, '0000-00-00', '0000-00-00', '', '', 'JL. KH AHMAD DAHLAN GG. KELINCI NO. 46 SUKAJADI HARJOSARI'),
('04.10-01-0015-01', 'HOTMA ', 'PARULIAN ', 'SITOHANG', 'LK', 'KK', 'PEKANBARU', '1967-02-04', 1, 'PEKANBARU', '1967-08-20', 1, 'PEKANBARU', '1984-03-11', 1, '1999-07-09', '0000-00-00', '0761-23554', '', 'JL. MELUR UJUNG/NENAS NO.15  SENAPELAN PADANG TERUBUK'),
('04.10-01-0015-02', 'NANI', 'MAGDALENA', 'NAPITUPULU', 'PR', 'IS', 'P. SIANTAR', '1970-07-06', 1, 'P. SIANTAR', '1971-05-30', 1, 'DKI', '1992-04-12', 1, '1999-07-09', '0000-00-00', '', '', 'JL. MELUR UJUNG/NENAS NO.15  SENAPELAN PADANG TERUBUK'),
('04.10-01-0015-031', 'GITA SHERLY', 'FEBIOLA', 'SITOHANG', 'PR', 'AN', 'PEKANBARU', '2004-05-13', 0, '', '0000-00-00', 0, '', '0000-00-00', 0, '0000-00-00', '0000-00-00', '', '', 'JL. MELUR UJUNG/NENAS NO.15  SENAPELAN PADANG TERUBUK'),
('04.10-01-0015-032', 'GAVRILA ', 'ANGELA KESIA', 'SITOHANG', 'PR', 'AN', 'PEKANBARU', '2000-05-10', 1, 'PEKANBARU', '2001-06-03', 0, '', '0000-00-00', 0, '0000-00-00', '0000-00-00', '', '', 'JL. MELUR UJUNG/NENAS NO.15  SENAPELAN PADANG TERUBUK'),
('04.10-01-0017-01', 'JEMRIF ', 'ED ', 'BANUNAEK', 'LK', 'KK', 'KUPANG/NTT', '1975-05-01', 1, 'KUPANG/NTT', '1975-12-24', 1, 'KUPANG/NTT', '1995-12-24', 1, '2009-07-20', '0000-00-00', '', '081365712635', 'JL. RUSA NO. 7  SUKAJADI HARJOSARI'),
('04.10-01-0017-02', 'DONNA ', 'RN', 'BARIMBING', 'PR', 'IS', 'MEDAN', '1984-12-13', 1, 'DOLOK MARAJA', '1986-10-26', 1, 'DOLOK MARAJA', '2009-07-12', 1, '2009-07-20', '0000-00-00', '', '085272554468', 'JL. RUSA NO. 7  SUKAJADI HARJOSARI'),
('04.10-01-0017-031', 'FREDERICO ', '', 'BANUNAEK', 'LK', 'AN', 'PEKANBARU', '2010-09-27', 0, '', '0000-00-00', 0, '', '0000-00-00', 0, '0000-00-00', '0000-00-00', '', '', 'JL. RUSA NO. 7  SUKAJADI HARJOSARI'),
('04.10-01-0018-031', 'YUDA ', '', 'PATILAWA', 'LK', 'AN', 'BENGKALIS', '1971-08-01', 1, 'BENGKALIS', '1905-05-25', 1, 'AMBARAWA', '0000-00-00', 0, '0000-00-00', '0000-00-00', '', '', 'JL. DURIAN/PEPAYA NO. 1  PULAU KARAM SUKAJADI'),
('04.10-01-0018-032', 'YOSEF LUKU', 'PRASETYO', '', 'LK', 'AN', 'PEKANBARU', '1980-10-09', 1, 'BENGKALIS', '1981-02-22', 1, 'TEMBILAHAN', '1981-02-22', 0, '0000-00-00', '0000-00-00', '', '', 'JL. DURIAN/PEPAYA NO. 1  PULAU KARAM SUKAJADI'),
('04.10-01-0018-04', 'JOHADI ', '', 'JOKANAN', 'LK', 'OT', 'SEMARANG', '1937-07-03', 1, '', '0000-00-00', 1, 'AMBARAWA', '1958-11-05', 3, '0000-00-00', '0000-00-00', '0761-25890', '', 'JL. DURIAN GG. PEPAYA I NO. 42 A  SUKAJADI PULAU KARAM'),
('04.10-01-0018-072', 'YENTI CAROLINA', 'YOSEPHA', '', 'PR', 'MN', 'PEKANBARU', '1980-08-30', 1, 'TEMBILAHAN', '2002-03-03', 1, 'TEMBILAHAN', '2002-03-03', 1, '2002-03-02', '0000-00-00', '', '', 'JL. DURIAN/PEPAYA NO. 1  PULAU KARAM SUKAJADI'),
('04.10-01-0019-01', 'JOSIAS ', 'MARTONO ', 'TAKDARE', 'LK', 'KK', 'SALATIGA', '1947-05-31', 1, 'PEKANBARU', '0000-00-00', 1, 'PEKANBARU', '0000-00-00', 1, '1975-05-03', '1975-05-03', '0761-29530', '0811751125', 'JL. CEMPAKA GG. SURYA 1 NO. 28 A  SUKAJADI SUKAJADI'),
('04.10-01-0019-02', 'TIAPUL', 'MAGDALENA', 'HUTABARAT', 'PR', 'IS', 'PD. SIDEMPUAN', '1950-12-05', 1, 'PD. SIDEMPUAN', '0000-00-00', 1, 'PD. SIDEMPUAN', '0000-00-00', 1, '1975-05-03', '1975-05-03', '', '', 'JL. CEMPAKA GG. SURYA 1 NO. 28 A  SUKAJADI SUKAJADI'),
('04.10-01-0019-032', 'ANDREAS', 'BENHAR NUGROHO', 'TAKDARE', 'LK', 'AN', 'PEKANBARU', '1977-10-04', 1, 'PEKANBARU', '0000-00-00', 1, 'DURI', '0000-00-00', 1, '0000-00-00', '2009-09-05', '', '08127687468', 'JL. CEMPAKA GG. SURYA 1 NO. 28 A  SUKAJADI SUKAJADI'),
('04.10-01-0019-033', 'ANITA', 'JOSEPHINE SETIATI', 'TAKDARE', 'PR', 'AN', 'PEKANBARU', '1979-03-14', 1, 'DUMAI', '0000-00-00', 1, 'DURI', '0000-00-00', 1, '0000-00-00', '2010-07-05', '', '', 'JL. CEMPAKA GG. SURYA 1 NO. 28 A  SUKAJADI SUKAJADI'),
('04.10-01-0019-034', 'ALICE', 'MARGARETTA', 'TAKDARE', 'PR', 'AN', 'PEKANBARU', '1983-05-20', 1, 'RUMBAI', '0000-00-00', 1, 'PEKANBARU', '0000-00-00', 0, '0000-00-00', '0000-00-00', '', '', 'JL. CEMPAKA GG. SURYA 1 NO. 28 A  SUKAJADI SUKAJADI'),
('04.10-01-0020-01', 'KASMANTA ', '', 'SINURAYA', 'LK', 'KK', 'SINGGA MANIK', '1942-05-10', 1, '', '0000-00-00', 1, 'KABANJAHE', '1961-06-18', 1, '1967-09-12', '0000-00-00', '', '081371721502', 'JL. MELUR UJUNG/NENAS NO. 6B  SENAPELAN PADANG TERUBUK'),
('04.10-01-0020-02', 'KASMIATI', '', 'GINTING', 'PR', 'IS', 'TANJUNG MORAWA', '1947-11-22', 1, 'KABANJAHE', '1961-06-18', 1, 'PEKANBARU', '1991-03-24', 1, '1967-09-12', '0000-00-00', '', '', 'JL. MELUR UJUNG/NENAS NO. 6B  SENAPELAN PADANG TERUBUK'),
('04.10-01-0020-031', 'JERRY', 'MEDIANTO', 'SINURAYA', 'LK', 'AN', 'PEKANBARU', '1970-07-05', 1, 'PEKANBARU', '1972-08-06', 1, 'PEKANBARU', '2002-03-24', 0, '0000-00-00', '0000-00-00', '', '', 'JL. MELUR UJUNG/NENAS NO. 6B  SENAPELAN PADANG TERUBUK'),
('04.10-01-0020-032', 'YUNIARTO', '', 'SINURAYA', 'LK', 'AN', 'PEKANBARU', '1971-07-26', 1, 'PEKANBARU', '0000-00-00', 1, 'PEKANBARU', '1993-04-05', 0, '0000-00-00', '0000-00-00', '', '', 'JL. MELUR UJUNG/NENAS NO. 6B  SENAPELAN PADANG TERUBUK'),
('04.10-01-0020-033', 'YAN ', 'MANNA PUTRA', 'SINURAYA', 'LK', 'AN', '', '0000-00-00', 1, 'PEKANBARU', '1981-12-25', 1, 'PEKANBARU', '0000-00-00', 0, '0000-00-00', '0000-00-00', '', '', 'JL. MELUR UJUNG/NENAS NO. 6B  SENAPELAN PADANG TERUBUK'),
('04.10-01-0021-01', 'MANAOR ', '', 'SIAHAAN', 'LK', 'KK', 'TEBING TINGGI', '1939-08-19', 1, 'HKI OMBUR', '1940-08-15', 1, 'HKI DOLOK', '1957-05-19', 1, '1963-06-03', '0000-00-00', '0761-22442', '081365707576', 'JL. PEPAYA NO. 13  SUKAJADI PULO KARAM'),
('04.10-01-0021-02', 'TIORIA', '', 'SIANIPAR', 'PR', 'IS', 'SIBORONG BORONG', '1945-08-17', 1, 'HKBP SIBORONG BORONG', '1946-06-12', 1, 'HKBP PEKAMIS DOLOK', '1959-06-28', 1, '1963-06-03', '0000-00-00', '', '081365707577', 'JL. PEPAYA NO. 13  SUKAJADI PULO KARAM'),
('04.10-01-0022-01', 'MANGAPUL ', '', 'NAINGGOLAN', 'LK', 'KK', 'PEKANBARU', '1978-05-12', 1, 'PEKANBARU', '0000-00-00', 1, 'DABO SINGKEP', '0000-00-00', 1, '2004-09-10', '2004-09-11', '', '081275723645', 'JL. RUSA NO. 14  SUKAJADI HARJOSARI'),
('04.10-01-0022-02', 'DEBY', 'NURSANTI', 'MANALU', 'PR', 'IS', 'DABO SINGKEP', '1980-03-20', 1, 'PEKANBARU', '0000-00-00', 1, 'PEKANBARU', '0000-00-00', 1, '2004-09-10', '2004-09-11', '', '08127687512', 'JL. RUSA NO. 14  SUKAJADI HARJOSARI'),
('04.10-01-0022-031', 'DESY', 'KANIA', 'NAINGGOLAN', 'PR', 'AN', 'PEKANBARU', '2005-12-01', 1, 'PEKANBARU', '2006-12-26', 0, '', '0000-00-00', 0, '0000-00-00', '0000-00-00', '', '', 'JL. RUSA NO. 14  SUKAJADI HARJOSARI'),
('04.10-01-0022-032', 'CISILLIA ', 'REGINA', 'NAINGGOLAN', 'PR', 'AN', 'PEKANBARU', '2007-06-16', 1, 'PEKANBARU', '2008-05-18', 0, '', '0000-00-00', 0, '0000-00-00', '0000-00-00', '', '', 'JL. RUSA NO. 14  SUKAJADI HARJOSARI'),
('04.10-01-0023-01', 'MAX ', 'ROBERT ', 'RUMENGAN', 'LK', 'KK', 'JAKARTA', '1959-11-24', 1, 'JAKARTA', '1960-12-25', 1, 'PEKANBARU', '1984-04-21', 1, '2001-02-16', '2001-02-16', '0761-861320', '0811762457', 'JL. NANGKA GG. HOP NO.7 SUKAJADI KAMPUNG MELAYU'),
('04.10-01-0023-02', 'KRISTIYANTI', 'LAURICA ', 'SIAGIAN', 'PR', 'IS', 'TANJUNG PINANG', '1969-11-05', 1, 'TANJUNG PINANG', '1970-06-07', 1, 'TANJUNG PINANG', '1987-03-22', 1, '2001-02-16', '2001-02-16', '', '', 'JL. NANGKA GG. HOP NO.7 SUKAJADI KAMPUNG MELAYU'),
('04.10-01-0023-031', 'RIKO', 'FEBRIAN', 'RUMENGAN', 'LK', 'AN', 'PEKANBARU', '2002-02-23', 1, 'PEKANBARU', '2002-05-19', 0, '', '0000-00-00', 0, '0000-00-00', '0000-00-00', '', '', 'JL. NANGKA GG. HOP NO.7 SUKAJADI KAMPUNG MELAYU'),
('04.10-01-0024-01', 'MELKY ', 'GUSLOW ', 'BANUNAEK', 'LK', 'KK', 'SOE, NTT', '1979-09-12', 1, 'HOINENO, NTT', '1979-12-25', 1, 'SOE, NTT', '0000-00-00', 1, '2008-02-03', '2009-04-15', '', '08127656452', 'JL. RUSA NO. 9  SUKAJADI HARJOSARI'),
('04.10-01-0024-02', 'NOVENTY', 'SETYANINGSIH', '', 'PR', 'IS', 'MAGELANG, JATENG', '1978-11-19', 1, 'MAGELANG', '1993-07-25', 1, '', '0000-00-00', 1, '2008-02-03', '2009-04-15', '', '081275857445', 'JL. RUSA NO. 9  SUKAJADI HARJOSARI'),
('04.10-01-0024-031', 'JESSICA', 'DERVIANA', 'BANUNAEK', 'PR', 'AN', 'PEKANBARU', '2008-11-01', 0, '', '0000-00-00', 0, '', '0000-00-00', 0, '0000-00-00', '0000-00-00', '', '', 'JL. RUSA NO. 9  SUKAJADI HARJOSARI'),
('04.10-01-0024-032', 'CECILLIA', 'AYUWARDANI', 'BANUNAEK', 'PR', 'AN', 'PEKANBARU', '2008-11-01', 0, '', '0000-00-00', 0, '', '0000-00-00', 0, '0000-00-00', '0000-00-00', '', '', 'JL. RUSA NO. 9  SUKAJADI HARJOSARI'),
('04.10-01-0024-033', 'CHRISTIAN', 'GRADY', 'BANUNAEK', 'LK', 'AN', 'PEKANBARU', '2012-11-14', 0, '', '0000-00-00', 0, '', '0000-00-00', 0, '0000-00-00', '0000-00-00', '', '', 'JL. RUSA NO. 9  SUKAJADI HARJOSARI'),
('04.10-01-0024-081', 'SERLI', 'MAYA', 'TAMELAN', 'PR', 'FA', 'SOE, NTT', '1989-07-03', 1, '', '0000-00-00', 0, '', '0000-00-00', 0, '0000-00-00', '0000-00-00', '', '', 'JL. RUSA NO. 9  SUKAJADI HARJOSARI'),
('04.10-01-0024-082', 'SOLEMAN', '', 'SEO', 'LK', 'FA', 'SOE, NTT', '1992-08-10', 1, '', '0000-00-00', 0, '', '0000-00-00', 0, '0000-00-00', '0000-00-00', '', '', 'JL. RUSA NO. 9  SUKAJADI HARJOSARI'),
('04.10-01-0024-083', 'IMER', 'SAFET', 'TAMELAN', 'LK', 'FA', 'SOE, NTT', '1990-03-01', 1, '', '0000-00-00', 0, '', '0000-00-00', 0, '0000-00-00', '0000-00-00', '', '', 'JL. RUSA NO. 9  SUKAJADI HARJOSARI'),
('04.10-01-0025-01', 'MIKAEL ', '', 'SAMOSIR', 'LK', 'KK', 'P. SAMOSIR', '1963-10-12', 1, 'P. SAMOSIR', '0000-00-00', 1, '', '0000-00-00', 1, '1995-09-30', '0000-00-00', '', '081378021044', 'JL. MUTIARA NO. 22  SENAPELAN PADANG TERUBUK'),
('04.10-01-0025-02', 'MONICA ', 'LINDA', 'NAIBAHO', 'PR', 'IS', 'MINAS', '1957-01-20', 1, 'DURI', '0000-00-00', 1, '', '0000-00-00', 1, '1995-09-30', '0000-00-00', '', '', 'JL. MUTIARA NO. 22  SENAPELAN PADANG TERUBUK'),
('04.10-01-0025-031', 'CHRISTINE', 'HELMY MONALISA', 'SAMOSIR', 'PR', 'AN', 'PEKANBARU', '1996-09-09', 1, 'PEKANBARU', '0000-00-00', 0, '', '0000-00-00', 0, '0000-00-00', '0000-00-00', '', '', 'JL. MUTIARA NO. 22  SENAPELAN PADANG TERUBUK'),
('04.10-01-0026-01', 'MIROS ', '', 'SINURAYA', 'LK', 'KK', 'KEBUN JAHE', '1948-12-31', 1, 'KEBUN JAHE', '0000-00-00', 1, 'KEBUN JAHE', '0000-00-00', 1, '0000-00-00', '0000-00-00', '0761-38867', '08127540604', 'JL. DAHLIA GG. PMI NO. 47A  SUKAJADI REJOSARI'),
('04.10-01-0026-031', 'MIKE', '', 'SINURAYA', 'LK', 'AN', 'PEKANBARU', '1978-06-08', 1, 'KEBUN JAHE', '0000-00-00', 1, 'PEKANBARU', '0000-00-00', 1, '0000-00-00', '0000-00-00', '', '', 'JL. DAHLIA GG. PMI NO. 47A  SUKAJADI REJOSARI'),
('04.10-01-0027-01', 'MULAWAN ', '', 'HUTAGAOL', 'LK', 'KK', 'P. SIANTAR', '1965-07-27', 1, 'TANJUNG BALAI', '1966-05-30', 1, 'PEKANBARU', '1982-06-30', 1, '1994-11-18', '0000-00-00', '0761-42440', '0811767903', 'JL. MUTIARA NO. 4  SENAPELAN PADANG TERUBUK'),
('04.10-01-0027-02', 'ROSWATI', '', 'NAPITUPULU', 'PR', 'IS', 'SEI PAKNING', '1964-04-17', 1, 'HKBP SIAK', '1994-10-30', 1, 'HKBP SIAK', '1994-10-30', 1, '1994-11-18', '0000-00-00', '', '', 'JL. MUTIARA NO. 4  SENAPELAN PADANG TERUBUK'),
('04.10-01-0027-031', 'TANTI', 'MULIATI', 'HUTAGAOL', 'PR', 'AN', 'PEKANBARU', '1996-01-22', 1, 'PEKANBARU', '1998-12-13', 0, '', '0000-00-00', 0, '0000-00-00', '0000-00-00', '', '', 'JL. MUTIARA NO. 4  SENAPELAN PADANG TERUBUK'),
('04.10-01-0027-032', 'LEO', 'TAN SAPUTRA', 'HUTAGAOL', 'LK', 'AN', 'PEKANBARU', '1998-07-30', 1, 'PEKANBARU', '1998-12-13', 0, '', '0000-00-00', 0, '0000-00-00', '0000-00-00', '', '', 'JL. MUTIARA NO. 4  SENAPELAN PADANG TERUBUK'),
('04.10-01-0028-033', 'DAMERIA', '', '', 'PR', 'AN', 'PEKANBARU', '1972-06-13', 1, 'PEKANBARU', '1982-05-20', 1, 'PEKANBARU', '1993-04-04', 0, '0000-00-00', '0000-00-00', '', '', 'JL. KAMBOJA GG. PURA CENDANA NO. 17  SUKAJADI SUKAJADI'),
('04.10-01-0028-034', 'NATALIA', '', '', 'PR', 'AN', 'PEKANBARU', '1995-12-09', 1, 'PEKANBARU', '1998-12-13', 0, '', '0000-00-00', 0, '0000-00-00', '0000-00-00', '', '', 'JL. KAMBOJA GG. PURA CENDANA NO. 17  SUKAJADI SUKAJADI'),
('04.10-01-0028-04', 'MURNIATI ', '', 'HUTABARAT', 'PR', 'OT', 'JAMBI', '1942-08-01', 1, 'PEKANBARU', '1982-04-10', 1, '', '0000-00-00', 2, '1988-06-29', '0000-00-00', '0761-47784', '', 'JL. KAMBOJA GG. PURA CENDANA NO. 17  SUKAJADI SUKAJADI'),
('04.10-01-0029-01', 'NIKOLAUS ', '', 'SINAY', 'LK', 'KK', 'AMBON', '1963-11-01', 1, 'AMBON', '0000-00-00', 1, 'AMBON', '0000-00-00', 1, '1990-09-27', '2007-11-29', '0761-848854', '081371248611', 'JL. CEMPAKA GG. SURYA I NO. 28B  SUKAJADI SUKAJADI'),
('04.10-01-0029-02', 'ESTERLINA ', 'ALENDALINA ', 'SINAY', 'PR', 'IS', 'AMBON', '1971-04-06', 1, 'AMBON', '0000-00-00', 1, 'AMBON', '0000-00-00', 1, '1990-09-27', '2007-11-29', '', '081365794204', 'JL. CEMPAKA GG. SURYA I NO. 28B  SUKAJADI SUKAJADI'),
('04.10-01-0029-031', 'STANY', 'GRACE', 'SINAY', 'PR', 'AN', 'AMBON', '1989-10-05', 1, 'AMBON', '1993-05-02', 1, 'AMBON', '2008-03-16', 0, '0000-00-00', '0000-00-00', '', '085282399158', 'JL. CEMPAKA GG. SURYA I NO. 28B  SUKAJADI SUKAJADI'),
('04.10-01-0029-032', 'FIORELLO', 'NEVAN', 'SINAY', 'LK', 'AN', 'PEKANBARU', '2011-03-24', 1, 'PEKANBARU', '2011-10-09', 0, '-', '0000-00-00', 0, '0000-00-00', '0000-00-00', '', '', 'JL. CEMPAKA GG. SURYA I NO. 28B  SUKAJADI SUKAJADI'),
('04.10-01-0029-033', 'ANNABELLE', 'SHARON', 'SINAY', 'PR', 'AN', 'PEKANBARU', '2012-12-15', 0, '', '0000-00-00', 0, '', '0000-00-00', 0, '0000-00-00', '0000-00-00', '', '', 'JL. CEMPAKA GG. SURYA I NO. 28B  SUKAJADI SUKAJADI'),
('04.10-01-0029-061', 'DIANA ', 'ISYELONE ', 'MUSKITTA', 'PR', 'KA', 'AMBON', '1979-09-14', 1, 'AMBON', '0000-00-00', 1, 'AMBON', '0000-00-00', 0, '0000-00-00', '0000-00-00', '', '085265529540', 'JL. CEMPAKA GG. SURYA I NO. 28B  SUKAJADI SUKAJADI'),
('04.10-01-0029-062', 'MARLEN', '', 'SINAY', 'PR', 'KA', 'AMBON', '1977-03-18', 1, 'AMBON', '0000-00-00', 1, 'AMBON', '0000-00-00', 0, '0000-00-00', '0000-00-00', '', '085365097422', 'JL. CEMPAKA GG. SURYA I NO. 28B  SUKAJADI SUKAJADI'),
('04.10-01-0030-01', 'NYOMAN ', 'SUAMBA YASA', '', 'LK', 'KK', 'BULELENG', '1955-10-24', 1, '', '0000-00-00', 1, '', '0000-00-00', 1, '1987-05-27', '0000-00-00', '0761-22919', '08127566625', 'JL. TERATAI GG. BUNGA RAYA NO. 97  SENAPELAN PADANG TERUBUK'),
('04.10-01-0030-02', 'RATNA', 'MEGAWATI', '', 'PR', 'IS', 'PEKANBARU', '1958-01-22', 1, 'PEKANBARU', '1958-05-11', 1, 'PEKANBARU', '1973-11-18', 1, '1987-05-27', '0000-00-00', '', '08127535928', 'JL. TERATAI GG. BUNGA RAYA NO. 97  SENAPELAN PADANG TERUBUK'),
('04.10-01-0030-031', 'SHERIN', 'ROSALIA', '', 'PR', 'AN', 'DENPASAR', '1999-08-18', 1, 'PEKANBARU', '2005-12-22', 0, '', '0000-00-00', 0, '0000-00-00', '0000-00-00', '', '083186805832', 'JL. TERATAI GG. BUNGA RAYA NO. 97  SENAPELAN PADANG TERUBUK'),
('04.10-01-0031-01', 'PANGIHUTAN ', '', 'SITUMORANG', 'LK', 'KK', 'MEDAN', '1958-11-15', 1, 'MEDAN', '1963-07-14', 1, 'JAKARTA', '1982-03-14', 1, '1983-03-28', '1983-03-28', '', '085274929486', 'JL. BALAM GG. PUYUH  SUKAJADI KAMPUNG MELAYU'),
('04.10-01-0031-02', 'HELMY', 'DIANA', '', 'PR', 'IS', 'JAKARTA', '1963-07-09', 1, 'JAKARTA', '1965-12-10', 1, 'JAKARTA', '1973-06-15', 1, '1983-03-28', '1983-03-28', '', '081378756234', 'JL. BALAM GG. PUYUH  SUKAJADI KAMPUNG MELAYU'),
('04.10-01-0031-031', 'MURNI', 'IRMAWATI', '', 'PR', 'AN', 'BANDUNG', '1984-08-07', 1, 'BANDUNG', '1986-11-17', 1, 'JAKARTA', '2004-06-17', 0, '0000-00-00', '0000-00-00', '', '083899165355', 'JL. BALAM GG. PUYUH  SUKAJADI KAMPUNG MELAYU'),
('04.10-01-0031-032', 'RICKY', 'LEONARDO', '', 'LK', 'AN', 'BANDUNG', '1985-10-24', 1, 'BANDUNG', '1987-11-20', 1, 'JAKARTA', '2008-07-10', 0, '0000-00-00', '0000-00-00', '', '081326052264', 'JL. BALAM GG. PUYUH  SUKAJADI KAMPUNG MELAYU'),
('04.10-01-0031-033', 'YOSUA', 'ANDREAS', '', 'LK', 'AN', 'BANDUNG', '1994-04-14', 1, 'BANDUNG', '1996-12-10', 0, '', '0000-00-00', 0, '0000-00-00', '0000-00-00', '', '', 'JL. BALAM GG. PUYUH  SUKAJADI KAMPUNG MELAYU'),
('04.10-01-0032-01', 'RICHARD ', '', 'PANJAITAN', 'LK', 'KK', 'PORSEA, TAPUT', '1940-05-10', 1, 'MEDAN', '0000-00-00', 1, 'MEDAN', '0000-00-00', 1, '1936-10-08', '0000-00-00', '', '', 'JL. KH. AHMAD DAHLAN GG. KELINCI NO. 46  SUKAJADI HARJOSARI'),
('04.10-01-0033-01', 'ROBIN ', '', 'HUTAGALUNG', 'LK', 'KK', 'SIMALUNGUN', '1963-09-07', 1, '', '0000-00-00', 0, '', '0000-00-00', 1, '0000-00-00', '0000-00-00', '0761-22309', '', 'JL. KETITIRAN NO. 10  SUKAJADI KAMPUNG MELAYU'),
('04.10-01-0033-02', 'SUWANTI', '', '', 'PR', 'IS', 'SIDOARJO', '1974-07-13', 1, '', '0000-00-00', 0, '', '0000-00-00', 1, '0000-00-00', '0000-00-00', '', '', 'JL. KETITIRAN NO. 10  SUKAJADI KAMPUNG MELAYU'),
('04.10-01-0033-031', 'ZELOT', 'AGRIFA', 'HUTAGALUNG', 'LK', 'AN', 'PALANGKARAYA', '1995-04-29', 1, 'PEKANBARU', '0000-00-00', 0, '', '0000-00-00', 0, '0000-00-00', '0000-00-00', '', '', 'JL. KETITIRAN NO. 10  SUKAJADI KAMPUNG MELAYU'),
('04.10-01-0033-032', 'DELLA', 'SARAFINA', 'HUTAGALUNG', 'PR', 'AN', 'PEKANBARU', '1997-10-24', 1, 'PEKANBARU', '0000-00-00', 0, '', '0000-00-00', 0, '0000-00-00', '0000-00-00', '', '', 'JL. KETITIRAN NO. 10  SUKAJADI KAMPUNG MELAYU'),
('04.10-01-0033-033', 'BRYAN', 'ZEFANYA', 'HUTAGALUNG', 'LK', 'AN', 'PEKANBARU', '2002-07-10', 1, 'PEKANBARU', '0000-00-00', 0, '', '0000-00-00', 0, '0000-00-00', '0000-00-00', '', '', 'JL. KETITIRAN NO. 10  SUKAJADI KAMPUNG MELAYU'),
('04.10-01-0034-01', 'SIDIRIA ', '', 'HURA', 'PR', 'KK', 'NIAS', '1967-07-05', 1, 'NIAS', '1967-09-10', 1, 'NIAS', '1984-07-01', 1, '0000-00-00', '0000-00-00', '', '081369625135', 'JL. DURIAN GG. KEDUNG SARI  NO. 30 G SUKAJADI KEDUNG SARI'),
('04.10-01-0034-031', 'KURNIAWAN', '', 'HAREFA', 'LK', 'AN', 'BATAM', '1988-11-04', 1, 'BATAM', '1989-06-11', 1, 'PEKANBARU', '2005-03-20', 0, '0000-00-00', '0000-00-00', '', '081371377759', 'JL. DURIAN GG. KEDUNG SARI  NO. 30 G SUKAJADI KEDUNG SARI'),
('04.10-01-0034-032', 'DEDDY ', 'KRISTIAWAN', 'HAREFA', 'LK', 'AN', 'TANJUNG BATU', '1992-03-12', 1, 'TANJUNG BATU', '1993-04-11', 1, 'PEKANBARU', '2004-04-05', 0, '0000-00-00', '0000-00-00', '', '085263588874', 'JL. DURIAN GG. KEDUNG SARI  NO. 30 G SUKAJADI KEDUNG SARI'),
('04.10-01-0034-033', 'WIRA', 'PUTRA', 'HAREFA', 'LK', 'AN', 'TANJUNG BATU', '1995-04-08', 1, 'TANJUNG BATU', '0000-00-00', 1, 'PEKANBARU', '2012-04-01', 0, '0000-00-00', '0000-00-00', '', '08526560682', 'JL. DURIAN GG. KEDUNG SARI  NO. 30 G SUKAJADI KEDUNG SARI'),
('04.10-01-0035-01', 'SIMON ', 'SUHARTO', '', 'LK', 'KK', 'PEKANBARU', '1966-08-27', 1, 'PEKANBARU', '1966-12-04', 0, '', '0000-00-00', 1, '1995-04-17', '0000-00-00', '0761-38304', '', 'JL. MELATI GG. ASTER NO. 18  HARJOSARI SUKAJADI'),
('04.10-01-0035-02', 'WANTIN', 'ROSTINI', '', 'PR', 'IS', 'RANAI', '1965-04-30', 1, 'PERAWANG', '1995-04-06', 0, '', '0000-00-00', 1, '1995-04-17', '0000-00-00', '', '', 'JL. MELATI GG. ASTER NO. 18  HARJOSARI SUKAJADI'),
('04.10-01-0035-031', 'NUGROHO', '', '', 'LK', 'AN', 'PEKANBARU', '1999-07-04', 1, 'PEKANBARU', '1999-12-26', 0, '', '0000-00-00', 0, '0000-00-00', '0000-00-00', '', '', 'JL. MELATI GG. ASTER NO. 18  HARJOSARI SUKAJADI'),
('04.10-01-0035-032', 'PANJI', 'PANGESTU', '', 'LK', 'AN', 'PEKANBARU', '1996-03-27', 1, 'PEKANBARU', '1997-12-13', 0, '', '0000-00-00', 0, '0000-00-00', '0000-00-00', '', '', 'JL. MELATI GG. ASTER NO. 18  HARJOSARI SUKAJADI'),
('04.10-01-0035-033', 'CHAIA', 'CHRISTIE', '', 'PR', 'AN', 'PEKANBARU', '2003-03-03', 1, 'PEKANBARU', '2002-02-26', 0, '', '0000-00-00', 0, '0000-00-00', '0000-00-00', '', '', 'JL. MELATI GG. ASTER NO. 18  HARJOSARI SUKAJADI'),
('04.10-01-0036-01', 'SINGGIH ', '', 'ATMOSUTARJO', 'LK', 'KK', 'BOYOLALI', '1946-08-06', 1, 'SEMARANG', '1970-08-31', 1, 'SEMARANG', '1970-08-31', 1, '1975-10-18', '1975-10-18', '0761-32810', '0812761124', 'JL. SELINDIT NO. 3  SUKAJADI KAMPUNG MELAYU'),
('04.10-01-0036-02', 'TRI', 'PUTRIYATI', '', 'PR', 'IS', 'PURWOKERTO', '1951-03-18', 1, 'CIMAHI', '1975-10-05', 1, 'CIMAHI', '1975-10-05', 1, '1975-10-18', '1975-10-18', '', '08126871904', 'JL. SELINDIT NO. 3  SUKAJADI KAMPUNG MELAYU'),
('04.10-01-0036-031', 'UTAMI', 'TRIE WAHYUNI', 'SINGGIH', 'PR', 'AN', 'RENGAT', '1985-11-26', 1, 'PEKANBARU', '1991-03-24', 1, 'PEKANBARU', '2002-03-24', 0, '0000-00-00', '0000-00-00', '', '081326179701', 'JL. SELINDIT NO. 3  SUKAJADI KAMPUNG MELAYU'),
('04.10-01-0037-01', 'SUDAR ', '', 'KALIONO', 'LK', 'KK', 'SURINAME', '1937-01-28', 1, 'PEKANBARU', '1958-12-28', 1, 'PEKANBARU', '1958-12-28', 1, '1955-01-27', '0000-00-00', '0761-38304', '', 'JL. MELATI GG. ASTER NO. 18  HARJOSARI SUKAJADI'),
('04.10-01-0037-02', 'MARTINI', '', 'BLEDOEG', 'PR', 'IS', 'SURINAME', '1933-02-15', 1, '', '1905-04-16', 1, 'SURINAME', '0000-00-00', 1, '0000-00-00', '0000-00-00', '', '', 'JL. MELATI GG. ASTER NO. 18  HARJOSARI SUKAJADI'),
('04.10-01-0037-031', 'YOSEF ', 'WIRATNO', '', 'LK', 'AN', 'DURI', '1962-07-12', 1, 'PEKANBARU', '1962-11-18', 1, 'SURINAME', '0000-00-00', 0, '0000-00-00', '0000-00-00', '', '', 'JL. MELATI GG. ASTER NO. 18  HARJOSARI SUKAJADI'),
('04.10-01-0038-01', 'HANDRIS ', '', 'TAMBOTO', 'LK', 'KK', '', '1948-11-01', 1, '', '0000-00-00', 1, '', '0000-00-00', 1, '0000-00-00', '0000-00-00', '', '', 'JL. PUTRI NILAM GG. PUTRI HIJAU NO. 3A  SUKAJADI KAMPUNG TENGAH'),
('04.10-01-0038-02', 'NURLINA', '', 'KAMINANG', 'PR', 'IS', 'PADANG', '1962-09-13', 1, 'PADANG', '0000-00-00', 1, 'PEKANBARU', '0000-00-00', 1, '0000-00-00', '0000-00-00', '', '081371002595', 'JL. PUTRI NILAM GG. PUTRI HIJAU NO. 3A  SUKAJADI KAMPUNG TENGAH'),
('04.10-01-0038-04', 'SURINI ', '', 'KAMINANG', 'PR', 'OT', 'PALEMBANG', '1945-10-05', 1, 'PADANG', '0000-00-00', 1, 'PEKANBARU', '0000-00-00', 1, '0000-00-00', '0000-00-00', '0761-46608', '', 'JL. PUTRI NILAM GG. PUTRI HIJAU NO. 3A  SUKAJADI KAMPUNG TENGAH'),
('04.10-01-0040-01', 'TEGUH ', 'SETIYADI ', 'SOEDIBYO', 'LK', 'KK', 'PURWOKERTO', '1967-09-01', 1, '', '0000-00-00', 1, '', '0000-00-00', 1, '0000-00-00', '0000-00-00', '', '085265483034', 'JL. RUSA  SUKAJADI HARJOSARI'),
('04.10-01-0040-02', 'RATNA', 'SARI', 'TINAMBUNAN', 'PR', 'IS', 'PEKANBARU', '1971-05-05', 1, '', '0000-00-00', 1, 'PEKANBARU', '0000-00-00', 1, '0000-00-00', '0000-00-00', '', '085271580400', 'JL. RUSA  SUKAJADI HARJOSARI'),
('04.10-01-0040-031', 'RANDY', 'ATMADJA', 'SETIYADI', 'LK', 'AN', 'PEKANBARU', '1998-11-23', 1, 'PEKANBARU', '0000-00-00', 0, '', '0000-00-00', 0, '0000-00-00', '0000-00-00', '', '', 'JL. RUSA  SUKAJADI HARJOSARI'),
('04.10-01-0040-032', 'PIETHA TIARA', 'LINGGA DEWI', 'SETIYADI', 'PR', 'AN', 'PEKANBARU', '2000-03-20', 1, 'PEKANBARU', '0000-00-00', 0, '', '0000-00-00', 0, '0000-00-00', '0000-00-00', '', '', 'JL. RUSA  SUKAJADI HARJOSARI'),
('04.10-01-0040-033', 'GRACESHELLA', 'TRI ANASYA', 'SETIYADI', 'PR', 'AN', 'PEKANBARU', '2004-06-09', 1, 'PEKANBARU', '0000-00-00', 0, '', '0000-00-00', 0, '0000-00-00', '0000-00-00', '', '', 'JL. RUSA  SUKAJADI HARJOSARI'),
('04.10-01-0041-01', 'TOEKIDJO ', 'HARDJO ', 'PAWIRO', 'LK', 'KK', 'MAGELANG', '1937-03-28', 1, 'PEKANBARU', '1976-12-25', 1, 'PEKANBARU', '1976-12-25', 3, '1959-01-12', '0000-00-00', '', '085263755814', 'JL. TULIP NO. 27  SUKAJADI HARJOSARI'),
('04.10-01-0042-01', 'YUNIOR ', 'ELRICO ', 'MARPAUNG', 'LK', 'KK', 'PEKANBARU', '1979-06-18', 1, 'PEKANBARU', '0000-00-00', 1, 'KERINCI', '0000-00-00', 1, '2010-10-05', '0000-00-00', '', '085376330003', 'JL. KUTILANG NO. 25  SUKAJADI KAMPUNG MELAYU'),
('04.10-01-0042-02', 'IMELDA', 'SEVENT', 'HUTAHAEAN', 'PR', 'IS', 'LAGUBOTI', '1984-11-07', 1, '', '0000-00-00', 1, '', '0000-00-00', 1, '0000-00-00', '0000-00-00', '', '085263770779', 'JL. KUTILANG NO. 25  SUKAJADI KAMPUNG MELAYU'),
('04.10-01-0042-031', 'GABRIEL', 'NATANAEL', 'MARPAUNG', 'LK', 'AN', 'PEKANBARU', '2011-07-02', 1, 'PEKANBARU', '2012-03-11', 0, '', '0000-00-00', 0, '0000-00-00', '0000-00-00', '', '', 'JL. KUTILANG NO. 25  SUKAJADI KAMPUNG MELAYU'),
('04.10-01-0042-032', 'CALVIN', 'YURICO MARCHELO', 'MARPAUNG', 'LK', 'AN', 'PEKANBARU', '2014-01-08', 0, '', '0000-00-00', 0, '', '0000-00-00', 0, '0000-00-00', '0000-00-00', '', '', ''),
('04.10-01-0043-01', 'ZULKIFLI ', 'ZAINUDIN', '', 'LK', 'KK', 'PEKANBARU', '1968-03-07', 1, 'PEKANBARU', '1996-08-11', 1, 'PEKANBARU', '1996-08-16', 1, '1997-05-05', '1998-08-18', '', '081276195333', 'JL. KIJANG NO. 27 SUKAJADI'),
('04.10-01-0043-02', 'OKTARIA', 'MEIKALINA', '', 'PR', 'IS', 'PEKANBARU', '1967-10-23', 1, 'PEKANBARU', '1967-12-24', 1, 'PEKANBARU', '1985-05-05', 1, '1997-05-05', '1998-08-18', '', '082172519727', 'JL. KIJANG NO. 27 SUKAJADI'),
('04.10-01-0043-031', 'ALEXANDER', 'JULIO', '', 'LK', 'AN', 'PEKANBARU', '1998-07-06', 1, 'PEKANBARU', '0000-00-00', 0, '', '0000-00-00', 0, '0000-00-00', '0000-00-00', '', '', 'JL. KIJANG NO. 27 SUKAJADI'),
('04.10-01-0043-032', 'LUSI', 'FEBRIANI', '', 'PR', 'AN', 'PEKANBARU', '2000-02-08', 1, 'PEKANBARU', '2000-05-07', 0, '', '0000-00-00', 0, '0000-00-00', '0000-00-00', '', '', 'JL. KIJANG NO. 27 SUKAJADI'),
('04.10-01-0043-033', 'RINI OKTARIANI', 'PUTRI', '', 'PR', 'AN', 'PEKANBARU', '2004-10-25', 1, 'PEKANBARU', '2004-12-26', 0, '', '0000-00-00', 0, '0000-00-00', '0000-00-00', '', '', 'JL. KIJANG NO. 27 SUKAJADI'),
('04.10-01-0044-01', 'KADARYONO', '', '', 'LK', 'KK', 'TANJUNG MENTAWAI', '1961-11-02', 1, '', '0000-00-00', 0, '', '0000-00-00', 1, '1991-07-22', '0000-00-00', '0761-885629', '0811769708', 'JL. KUTILANG NO. 11, SUKAJADI KAMPUNG MELAYU'),
('04.10-01-0044-02', 'KURNIA', 'SWITA ', 'SARAGIH', 'PR', 'IS ', 'MEDAN', '1965-05-12', 1, '', '0000-00-00', 0, '', '0000-00-00', 1, '1991-07-22', '0000-00-00', '', '', 'JL. KUTILANG NO. 11, SUKAJADI KAMPUNG MELAYU'),
('04.10-01-0044-031', 'KINANTI', 'SHINTA ', 'DEBORA', 'PR', 'AN', 'TEBING TINGGI', '1992-04-30', 1, '', '0000-00-00', 0, '', '0000-00-00', 0, '0000-00-00', '0000-00-00', '', '', 'JL. KUTILANG NO. 11, SUKAJADI KAMPUNG MELAYU'),
('04.10-01-0044-032', 'KRISAN', 'FARRAETTY', '', 'PR', 'AN', 'MEDAN', '1995-05-29', 1, '', '0000-00-00', 0, '', '0000-00-00', 0, '0000-00-00', '0000-00-00', '', '', 'JL. KUTILANG NO. 11, SUKAJADI KAMPUNG MELAYU'),
('04.10-01-0044-033', 'KEVIN ', 'NOEL', 'ANUGERAH', 'LK', 'AN', 'MEDAN', '1996-12-12', 1, '', '0000-00-00', 0, '', '0000-00-00', 0, '0000-00-00', '0000-00-00', '', '', 'JL. KUTILANG NO. 11, SUKAJADI KAMPUNG MELAYU'),
('04.10-01-0045-01', 'KIM ', '', 'SUN', 'LK', 'KK', '', '1979-08-17', 1, '', '0000-00-00', 0, '', '0000-00-00', 1, '1998-03-14', '0000-00-00', '', '', 'JL. ANGKASA GG. ANGKASA III UJUNG NO.   AIR HITAM PAYUNG SEKAKI'),
('04.10-01-0045-02', 'SANDY', '', 'MANANGGEL', 'PR', 'IS', '', '1976-05-28', 1, '', '0000-00-00', 0, '', '0000-00-00', 1, '1998-03-15', '0000-00-00', '', '', 'JL. ANGKASA GG. ANGKASA III UJUNG NO.   AIR HITAM PAYUNG SEKAKI'),
('04.10-01-0045-031', 'VANESSA', 'SRINI GRACIA', '', 'PR', 'AN', '', '1998-07-02', 0, '', '0000-00-00', 0, '', '0000-00-00', 0, '0000-00-00', '0000-00-00', '', '', 'JL. ANGKASA GG. ANGKASA III UJUNG NO.   AIR HITAM PAYUNG SEKAKI'),
('04.10-01-0045-032', 'AGATHA', 'CRISTY GRACIA', '', 'PR', 'AN', '', '2005-07-15', 0, '', '0000-00-00', 0, '', '0000-00-00', 0, '0000-00-00', '0000-00-00', '', '', 'JL. ANGKASA GG. ANGKASA III UJUNG NO.   AIR HITAM PAYUNG SEKAKI'),
('04.10-01-0045-033', 'EGAN', 'IMANUEL KIMDY', '', 'LK', 'AN', '', '2010-09-16', 0, '', '0000-00-00', 0, '', '0000-00-00', 0, '0000-00-00', '0000-00-00', '', '', 'JL. ANGKASA GG. ANGKASA III UJUNG NO.   AIR HITAM PAYUNG SEKAKI'),
('04.10-01-0046-01', 'WELLY ', 'JAVANICA ', 'PANJAITAN', 'LK', 'KK', '', '1981-08-01', 1, '', '0000-00-00', 0, '', '0000-00-00', 1, '0000-00-00', '0000-00-00', '', '', 'JL. KUTILANG NO. 32 SUKAJADI KAMPUNG MELAYU'),
('04.10-01-0046-02', 'NATHASIA', 'MAUREEN', '', 'PR', 'IS', '', '1984-12-03', 1, '', '0000-00-00', 0, '', '0000-00-00', 1, '0000-00-00', '0000-00-00', '', '', 'JL. KUTILANG NO. 32 SUKAJADI KAMPUNG MELAYU'),
('04.10-01-0046-031', 'CHRISTIAN', 'JEREMY', 'PANJAITAN', 'LK', 'AN', '', '2005-05-02', 0, '', '0000-00-00', 0, '', '0000-00-00', 0, '0000-00-00', '0000-00-00', '', '', 'JL. KUTILANG NO. 32 SUKAJADI KAMPUNG MELAYU'),
('04.10-01-0046-032', 'KAYLA', 'ALLYSHA ELIZABETH', 'PANJAITAN', 'PR', 'AN', '', '2006-12-05', 0, '', '0000-00-00', 0, '', '0000-00-00', 0, '0000-00-00', '0000-00-00', '', '', 'JL. KUTILANG NO. 32 SUKAJADI KAMPUNG MELAYU'),
('04.10-01-0046-033', 'YOHANNA', 'AUDREY CALLISTA', 'PANJAITAN', 'PR', 'AN', '', '2008-11-06', 0, '', '0000-00-00', 0, '', '0000-00-00', 0, '0000-00-00', '0000-00-00', '', '', 'JL. KUTILANG NO. 32 SUKAJADI KAMPUNG MELAYU'),
('04.10-06-0009-01', 'DENOVMAN ', '', 'SINURAYA', 'LK', 'KK', 'PEKANBARU', '1975-01-08', 1, 'PEKANBARU', '1981-12-25', 1, 'PEKANBARU', '1993-04-05', 1, '2004-08-06', '0000-00-00', '', '', 'JL. MELATI INDAH / BUNGA TANJUNG PERUM PONDOK RATU BLOK D NO. 4, DELIMA - TAMPAN'),
('04.10-06-0009-02', 'YUNITA', 'DEWI', '', 'PR', 'IS', 'P. SIANTAR', '1984-09-17', 1, '', '0000-00-00', 1, '', '0000-00-00', 1, '2004-08-06', '0000-00-00', '', '', 'JL. MELATI INDAH / BUNGA TANJUNG PERUM PONDOK RATU BLOK D NO. 4, DELIMA - TAMPAN'),
('04.10-06-0009-031', 'NOVITA', 'SARI', 'SINURAYA', 'PR', 'AN', 'PEKANBARU', '2004-11-20', 1, 'PEKANBARU', '2004-12-26', 0, '', '0000-00-00', 0, '0000-00-00', '0000-00-00', '', '', 'JL. MELATI INDAH / BUNGA TANJUNG PERUM PONDOK RATU BLOK D NO. 4, DELIMA - TAMPAN');

-- --------------------------------------------------------

--
-- Struktur dari tabel `tbl_page`
--

CREATE TABLE IF NOT EXISTS `tbl_page` (
  `id` int(9) unsigned NOT NULL AUTO_INCREMENT,
  `parent_id` int(9) unsigned NOT NULL,
  `title` varchar(128) NOT NULL,
  `target` enum('#','page','category') NOT NULL,
  `menu_title` varchar(128) NOT NULL,
  `content` longtext NOT NULL,
  `sequence` int(11) NOT NULL DEFAULT '0',
  `seo_title` text NOT NULL,
  `meta` text NOT NULL,
  `url` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=5 ;

--
-- Dumping data untuk tabel `tbl_page`
--

INSERT INTO `tbl_page` (`id`, `parent_id`, `title`, `target`, `menu_title`, `content`, `sequence`, `seo_title`, `meta`, `url`) VALUES
(1, 0, 'Tentang Kami', 'page', 'tentang-kami', '', 0, '', '', ''),
(2, 1, 'Visi Misi', 'page', 'visi-misi', '<h2 style=\\"font-style:italic;\\">VISI GPIB</h2>\\r\\n\\r\\n<p>&#39;GPIB menjadi gereja yang mewujudkan damai sejahtera bagi seluruh ciptaanNya&#39;</p>\\r\\n\\r\\n<p>&nbsp;</p>\\r\\n\\r\\n<h2 style=\\"font-style:italic;\\">MISI GPIB</h2>\\r\\n\\r\\n<p>Menempatkan Tuhan Yesus Kristus, Juru Selamat manusia sebagai Kepala Gereja.&nbsp;</p>\\r\\n\\r\\n<p>Mewujudkan kehadiran GPIB yang membawa corak damai sejahtera Allah dan menjadi berkat di tengah - tengah masyarakat dan dunia.&nbsp;</p>\\r\\n\\r\\n<p>Membangun suatu Jemaat Misioner yang bertumbuh, dewasa dalam iman. Kehidupannya adalah teladan serta memberi kontribusi nyata bagi kemajuan gereja, masyarakat dan bangsa Indonesia dalam suatu semangat oikumenis dan Nasional.</p>\\r\\n\\r\\n<p>&nbsp;</p>\\r\\n\\r\\n<h2 style=\\"font-style:italic;\\">MOTO GPIB&nbsp;</h2>\\r\\n\\r\\n<p>&#39;Dan orang akan datang dari timur dan barat dan dari utara dan selatan dan mereka duduk makan di dalam Kerajaan Allah&#39;. (Lukas 13 : 29)</p>\\r\\n', 0, '', '', 'page/visi-misi'),
(3, 1, 'Sejarah', 'category', '4', '', 0, '', '', 'category/4'),
(4, 1, 'Pemahaman Iman GPIB', 'page', '', '<h2 style=\\"font-style:italic;\\">I KESELAMATAN</h2>\\r\\n\\r\\n<p>KAMI MENGAKU,&nbsp;</p>\\r\\n\\r\\n<ol>\\r\\n	<li>Bahwa Allah yang esa 1) dengan FirmanNya dalam kasihNya yang tiada tara telah memulai karya keselamatan bagi 2) alam semesta 3) sejak awal Penciptaan 4) dan setelah kejatuhan manusia dalam dosa 5). Allah meneruskan karyaNya untuk memelihara alam semesta dari derita dan maut 6). Karya keselamatan ini berlangsung sampai pada akhir zaman 7).&nbsp;</li>\\r\\n	<li>Bahwa Yesus Kristus 1) telah mati, bangkit dan naik ke surga 2) menjamin keselamatan orang percaya dan membeba-skannya dari kuasa dosa 3), derita dan maut 4). Dengan demikian relasi manusia dengan Allah dan relasi manusia dengan sesama ciptaan-Nya telah dipulihkan. Hal itu akan senantiasa kami peringati melalui sakramen: Baptisan 5) dan Perjamuan 6).&nbsp;</li>\\r\\n	<li>Bahwa dalam 1) karya keselamatan iAllah telah memanggil 2) Abraham 3) menjadi umat Perjanjian Lama, juga Israel dari perhambaan di Mesir dan menyelamatkannya 4) dari kepunahan. Allah meneruskan 5) kasih setiaNya de-ngan melindungi dan menuntun umatNya kembali yang terserak dan tercerai berai di tanah pembuangan 6)&nbsp;</li>\\r\\n	<li>Bahwa dalam karya keselamatan melalui Yesus Kristus, Allah telah menyelamatkan dan menghimpun 1) umat Perjanjian Baru 2) yaitu Gereja 3) yang diutus-Nya untuk memberitakan Injil 4) dan menghadirkan tanda-tanda kerajaan Allah 5) di atas bumi.&nbsp;</li>\\r\\n	<li>Bahwa oleh kasihNya yang tiada tara 1), Allah telah mewujud nyatakan keselamatan itu sepenuhnya melalui pekerjaan Yesus Kristus 2). Supaya setiap orang yang percaya kepadaNya tidak binasa melainkan memperoleh hidup yang kekal 3).&nbsp;</li>\\r\\n	<li>Bahwa Yesus Kristus yang adalah Raja 1) dari segala raja dan Tuan dari segala tuan 2) akan menyatakan kepenuhan Keselamatan 3) pada saat Ia datang kembali kelak sebagai Hakim 4) dan Raja yang duduk disebelah kanan Allah Bapa yang Maha Kuasa.5)&nbsp;</li>\\r\\n	<li>Bahwa keselamatan yang dikerjakan Kristus terbuka bagi seluruh umat yang ada di muka bumi yang terdiri dari berbagai suku- bangsa. Dalam kasih-Nya yang tiada tara Allah mengaruniakan keselamatan, yakni: kemer-dekaan 1) kepada bangsa Indonesia. Sebagai bangsa yang dimerdekakan bertanggung jawab mengupayakan pembebasan dari ketidak adilan 2), perusakan alam 3) dan pelecehan hak asasi manusia 4), kemerosotan etis-moral 5) dan bentuk penindasan lainnya.&nbsp;</li>\\r\\n	<li>Bahwa melalui Roh Kudus, Allah menuntun 1) orang percaya mengakui 2) Yesus Kristus selaku Tuhan dan Juruslamat 3) dalam pergumulannya di dunia.&nbsp;</li>\\r\\n</ol>\\r\\n\\r\\n<h2 style=\\"font-style:italic;\\">II - GEREJA</h2>\\r\\n\\r\\n<ol>\\r\\n	<li>Bahwa Allah Bapa telah memanggil dan menghimpun 1) dari antara bangsa - bangsa suatu umat 2) bagi Diri-Nya untuk menjadi berkat 3).&nbsp;</li>\\r\\n	<li>Bahwa panggilan itu dilanjutkan melalui Anak-Nya, yaitu Yesus yang adalah Tuhan 1). Dialah yang memanggil dan menjadi dasar 2) terbentuknya umat yang baru, yaitu Gereja 3).&nbsp;</li>\\r\\n	<li>Bahwa sepanjang sejarah dan di manapun di dunia, dari utara, selatan, barat dan timur, 1) orang-orang percaya dipanggil dan dituntun oleh Roh Kudus 2) untuk menjadi satu persekutuan 3) yang menjalankan tugas pelayanan, dan kesaksian 4).&nbsp;</li>\\r\\n	<li>Bahwa Yesus Kristus adalah Kepala Gereja 1) dan Gereja sebagai tubuh-Nya 2) yang rapi tersusun 3), dan segala sesuatu di dalamnya harus diselenggarakan secara tertib dan teratur 4).&nbsp;</li>\\r\\n	<li>Bahwa Gereja terpanggil untuk senantiasa menyata-kan keesaannya 1), supaya dunia percaya bahwa Allah Bapa telah mengutus Yesus Kristus 2), untuk menjalankan karya keselamatan bagi dunia 3) ini.&nbsp;</li>\\r\\n	<li>Bahwa keberadaan Gereja sebagai umat Allah terus menerus mengalami pembaharuan 1) bersama dan dengan seluruh ciptaan menyongsong penggenapan pemerintahan Allah .</li>\\r\\n	<li>Bahwa kendatipun Gereja terpanggil menghadirkan tanda-tanda Pemerintahan Allah 1), tetapi Gereja bukan Pemerintahan Allah itu sendiri 2).&nbsp;</li>\\r\\n	<li>Bahwa Gereja Protestan di Indonesia bagian Barat 1) bersama Gereja-Gereja lain adalah perwujudan dari Gereja Yesus Kristus 2) yang esa , kudus , am dan rasuli 3) yang berada dan berkarya di Indonesia yang beragam.&nbsp;</li>\\r\\n	<li>Bahwa Tuhan yang memanggil dan menetapkan para pelayan-Nya 1) sebagai Presbiter 2) yang berjalan bersama-sama 3) untuk memperlengkapi warga 4) GPIB yang missioner 5) sebagai manusia yang utuh.&nbsp;</li>\\r\\n</ol>\\r\\n\\r\\n<h2 style=\\"font-style:italic;\\">III - MANUSIA&nbsp;</h2>\\r\\n\\r\\n<ol>\\r\\n	<li>Bahwa manusia 1): laki dan perempuan 2), diciptakan sepadan 3) oleh Allah menurut rupa dan gambar-Nya 4).&nbsp;</li>\\r\\n	<li>Bahwa manusia diciptakan Allah sebagai mahluk religius 1) dan makhluk sosial 2) yang diberikan kemampuan 3) untuk membangun relasi secara positif dengan sesamanya demi kebersamaan dan kesejahteraan seluruh ciptaan-Nya.&nbsp;</li>\\r\\n	<li>Bahwa manusia laki-laki dan perempuan disatukan dalam pernikahan 1) untuk saling mengasihi dan melengkapi 4).&nbsp;</li>\\r\\n	<li>Bahwa manusia bertanggung-jawab untuk bekerja 1) dalam rangka memelihara dan melestarikan, 2) alam. Untuk menunaikan tugas yang mulia ini manusia maupun struktur masyarakatnya tidak boleh disanjung dan dipuja 3).&nbsp;</li>\\r\\n	<li>Bahwa manusia diberi kemampuan dan wewenang menata-layani alam 1) berserta isinya; kemampuan dan wewenang ini dilaksanakannnya dalam keseimbangan di antara kebebasan dan tanggung-jawab 2), dan di antara hak dan kewajiban 3).&nbsp;</li>\\r\\n	<li>Bahwa karena keinginannya manusia 1) menyalahgunakan kuasa 2) dan tanggung-jawabnya, sehingga ia jatuh dalam dosa 3) menyebabkan rusaknya hubungan 4) dengan Allah, sesama dan alam.&nbsp;</li>\\r\\n	<li>Bahwa manusia memerlukan anugerah pembaruan 1), agar dapat melanjutkan pekerjaanNya hingga pemenuhan kerajaan Allah 2).&nbsp;</li>\\r\\n	<li>Bahwa hanya oleh kemurahan Allah 1) melalui Yesus Kristus dan di dalam persekutuan 2) dengan Roh Kudus, martabat manusia sebagai gambar Allah 3) dipulihkan kembali, sehingga ia dapat menghayati dan menikmati hidup kekal 4) dalam kehidupan yang sekarang ini maupun dalam kehidupan yang akan datang.&nbsp;</li>\\r\\n</ol>\\r\\n\\r\\n<h2 style=\\"font-style:italic;\\">IV - ALAM DAN SUMBER DAYA&nbsp;</h2>\\r\\n\\r\\n<ol>\\r\\n	<li>Bahwa Allah menciptakan alam dan sumber daya-nya 1). Allah mempercayakan pengelolaannya kepada negara 2) dengan penuh tanggung jawab 3) demi kesejahteraan 4) manusia dan kelangsungan hidup sesama ciptaanNya.&nbsp;</li>\\r\\n	<li>Bahwa kekuatan-kekuatan alam 1) yang kelihatan dan yang tidak kelihatan, takluk pada kuasa Allah dan karena itu alam tidak boleh disembah 2).&nbsp;</li>\\r\\n	<li>Bahwa alam dan sumber dayanya telah dipulihkan oleh Yesus Kristus 1). Karena itu manusia yang telah didamaikan dan dipulihkan, wajib memelihara alam dan sumber dayanya dengan penuh perhatian dan rasa tanggung jawab&nbsp;</li>\\r\\n	<li>Bahwa dengan ilmu pengetahuan dan teknologi 1), manusia boleh meneliti dan mengelola alam beserta sumber dayanya, secara tepat guna sehingga alam memiliki kesempatan untuk memperbaharui dirinya dan berdaur ulang 2).&nbsp;</li>\\r\\n	<li>Bahwa oleh karena kuasa dosa, manusia cenderung untuk menguasai alam bagi kepentingan dan keuntungan pribadi, sehingga terjadi benturan kepentingan yang mengakibatkan dampak kerusakan alam. Hanya oleh pendamaian antara Allah dan manusia yang dilaksanakan dengan perantaraan Tuhan Yesus Kristus, maka manusia sebagai ciptaan baru 1) dapat melihat kembali pentingnya alam sebagai rumah dan sarana kehidupan bagi segala mahluk.&nbsp;</li>\\r\\n	<li>Bahwa karena pembaruan Roh Kudus 1), Gereja memiliki kewajiban moral 2) untuk bersama-sama pemerintah dan bangsa-bangsa berusaha menata ekologi dan mencegah pengrusakan alam.&nbsp;</li>\\r\\n</ol>\\r\\n\\r\\n<h2 style=\\"font-style:italic;\\">V - NEGARA DAN BANGSA&nbsp;</h2>\\r\\n\\r\\n<ol>\\r\\n	<li>Bahwa Allah, sebagai Sumber Kuasa, memberikan kuasa kepada pemerintah bangsa-bangsa guna mendatang-kan keadilan dan kesejahteraan, memelihara ketertib-an serta mencegah dan meniadakan kekacauan dan kejahatan 1).Dengan demikian sebagai hamba Allah 2), setiap pemerintah wajib mempertanggung jawabkan kuasa tersebut kepada Allah.&nbsp;</li>\\r\\n	<li>Bahwa pemerintah dan negara menjalankan kuasa dan wewenang di bawah terang Tuhan Yesus Kristus, yang berfirman: &quot;berilah kepada kaisar apa yang kaisar punya dan kepada Allah apa yang Allah punya&quot; 1) Dengan demikian pemerintah dan negara mempunyai otonomi 2), tetapi otonomi ini tidak dapat mengatasi otonomi Gereja sebagai tubuh Kristus. Oleh karena kaisar berada di bawah Allah.&nbsp;</li>\\r\\n	<li>Bahwa kuasa yang diberikan kepada pemerintah itu dapat disalahgunakan karena dijadikan sebagai tujuan, hingga timbul kelaliman, kejahatan dan keresahan 1). Jika terjadi demikian maka sebagai Hakim dan Raja 2) Tuhan Yesus Kristus yang duduk di sebelah kanan Allah 3) akan menghakimi pemerintah pemerintah dan penguasa 4).&nbsp;</li>\\r\\n	<li>Bahwa Roh Kudus yang adalah Roh keberanian akan menolong orang percaya untuk lebih taat kepada Allah dari pada kepada manusia 1). Seperti yang telah disaksikan oleh para Rasul ; oleh karena itu Gereja terpanggil memper-dengarkan suara kenabian 2) terhadap masalah negara, bangsa, dan masyarakat.&nbsp;</li>\\r\\n	<li>Bahwa berdasarkan tuntunan Roh Kudus, warga jemaat yang adalah sekaligus warga negara wajib menaati undang-undang dan penjabarannya yang telah menjadi ketetapan bersama 1), namun ia wajib memberi saran-saran perbaikan secara kritis dan konstruktif lewat saluran saluran pengawasan demi keadilan dan kesejahteraan bangsa.2)&nbsp;</li>\\r\\n	<li>Bahwa berdasarkan tuntunan Roh Kudus, warga jemaat yang adalah sekaligus warga negara 1) perlu membina rasa kebersamaan sebagai satu bangsa 2) yaitu Indonesia, membangun saling pengertian dan toleransi dalam rangka menghayati kerukunan 3) nasional, dan meng-galang kemajuan bersama 4) bagi rakyat Indonesia.&nbsp;</li>\\r\\n	<li>Bahwa berdasarkan tuntunan Roh Kudus, warga jemaat yang adalah sekaligus warga negara, di dalam kehidupan bernegara, berbangsa, dan bermasyarakat, perlu mem-bangun rasa persatuan dan kesatuan 1) yang tidak merusak kebhinekaan dan kesetaraan 2) yang telah menjadi bagian dari masyarakat warga ( civil -society ), di mana hak - hak asasi manusia dijunjung tinggi 3).&nbsp;</li>\\r\\n</ol>\\r\\n\\r\\n<h2 style=\\"font-style:italic;\\">VI - MASADEPAN&nbsp;</h2>\\r\\n\\r\\n<ol>\\r\\n	<li>Bahwa Allah dalam karya penyelamatan dan penciptaanNya menghantar orang percaya dari satu titik sejarah ke titik sejarah yang baru sehingga masa depan senantiasa tercakup dalam apa yang dibuatnya pada masa kini dan masa lalu 1).&nbsp;</li>\\r\\n	<li>Bahwa kedatangan Yesus Kristus sebagai Tuhan dan Juruselamat ke dalam dunia mem-berikan jaminan dan harapan yang pasti bagi orang yang percaya.&nbsp;</li>\\r\\n	<li>Bahwa Yesus Kristus adalah Tuhan 1) yang menjadi pusat ibadah 2) dan harapan 3) manusia dari zaman ke zaman dan Dia juga harapan mahluk lainnya,4) karena Dia-lah yang akan mendatangkan langit baru dan bumi baru 5) dimana derita dan maut tidak akan ada lagi tanpa Dia dunia tidak memiliki pengharapan 6)&nbsp;</li>\\r\\n	<li>Bahwa kebangkitan Yesus Kristus 1) maka orang percaya akan dibangkitkan dari kemati-an 2) dan dikumpulkan bersama-sama Dia 3) dalam keadaan yang Mulia 4). Oleh sebab itu maut bukanlah kata akhir dalam segala sesuatu melainkan hidup dalam kuasa kasih Yesus 5)&nbsp;</li>\\r\\n	<li>Bahwa Roh Kudus adalah roh pengharapan, akan menolong orang percaya untuk tetap berpaut pada kasih Kristus dan tidak ada suatu kuasa apapun yang dapat memisahkan orang percaya dari kasih Kristus 1). Apa yang dijanjikan kepada orang percaya untuk masa depan sudah mulai dialami pada masa kini 2), oleh karena sekarangpun orang percaya sudah hidup di dalam pengharapan 3)&nbsp;</li>\\r\\n	<li>Bahwa Roh Kudus yang adalah Roh masa depan menyadarkan orang percaya pada panggilan-Nya menjaga keutuhan dari bangsa dan negara 1) untuk mengisi kurun waktu menjelang masadepan yang pasti 2) itu dengan sikap, tindakan dan karya yang menghadirkan keadilan dan kebenaran berdasarkan kasih serta pemulihan 3) pemenuhan janji Allah akan langit baru dan bumi baru.&nbsp;</li>\\r\\n</ol>\\r\\n\\r\\n<h2 style=\\"font-style:italic;\\">VII - FIRMAN ALLAH&nbsp;</h2>\\r\\n\\r\\n<ol>\\r\\n	<li>Bahwa dengan perantaraan firman-Nya 1) Allah telah mencip-takan 2) langit dan bumi serta isinya. Firman Allah berkuasa 3) untuk mengubah dan membaharui. 4).&nbsp;</li>\\r\\n	<li>Bahwa Firman Allah telah menjadi manusia 1) di dalam dan melalui Yesus Kristus.&nbsp;</li>\\r\\n	<li>Bahwa dengan terang Roh Kudus, persekutuan orang percaya menetapkan tulisan-tulisan 1) yang memberitakan per-buatan Allah serta respon manusia terhadap tindakan Allah pada kurun waktu tertentu.&nbsp;</li>\\r\\n	<li>Bahwa dengan tuntunan Roh Kudus para penulis Alkitab menceritakan dan memberitakan perbuatan-perbuatan besar Allah dalam bentuk tulisan pada suatu kurun waktu tertentu dan juga respons manusia terhadap tindakan-tindakan Allah pada kurun waktu tertentu 3)</li>\\r\\n</ol>\\r\\n', 0, '', '', '#');

-- --------------------------------------------------------

--
-- Struktur dari tabel `tbl_slider`
--

CREATE TABLE IF NOT EXISTS `tbl_slider` (
  `slider_id` int(5) NOT NULL AUTO_INCREMENT,
  `slider_path` varchar(180) NOT NULL,
  `slider_title` varchar(80) NOT NULL,
  `slider_caption` varchar(120) NOT NULL,
  `slider_img` varchar(255) NOT NULL,
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`slider_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=5 ;

--
-- Dumping data untuk tabel `tbl_slider`
--

INSERT INTO `tbl_slider` (`slider_id`, `slider_path`, `slider_title`, `slider_caption`, `slider_img`, `created_at`) VALUES
(3, 'Slider', 'Bagi Tuhan Tak ada yang mustahil', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit,', 'ciputranews_1360028588.jpg', '2015-06-13 21:34:57'),
(4, 'Slider', 'Hadapi Semua Dengan Senyuman', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit,', '603074_10200797453925873_1917385995_n_wide.jpg', '2015-06-13 21:36:05');

-- --------------------------------------------------------

--
-- Struktur dari tabel `tbl_users`
--

CREATE TABLE IF NOT EXISTS `tbl_users` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `username` varchar(255) NOT NULL DEFAULT '',
  `email` varchar(255) NOT NULL DEFAULT '',
  `password` varchar(255) NOT NULL DEFAULT '',
  `fullname` varchar(255) NOT NULL,
  `avatar` varchar(255) DEFAULT 'default.jpg',
  `created_at` datetime NOT NULL,
  `updated_at` datetime DEFAULT NULL,
  `is_admin` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `is_confirmed` tinyint(1) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=4 ;

--
-- Dumping data untuk tabel `tbl_users`
--

INSERT INTO `tbl_users` (`id`, `username`, `email`, `password`, `fullname`, `avatar`, `created_at`, `updated_at`, `is_admin`, `is_confirmed`) VALUES
(1, 'samson', 'samson@sinaga.or.id', '$2y$10$Nf4j/5ptH2EYAxvDzr0iNODQbDP3OqRE2hPJ/RucyYCY5LUbIkOJG', 'Samson Sinaga', 'default.jpg', '2015-06-05 03:29:45', NULL, 1, 1),
(2, 'victor', 'victorsiahaan03@gmail.com', '$2y$10$RtRdVt1krlAg4LzZITEbEuydto1iUIsuug0gJzkp9tymz0DPIbx72', 'Victor Siahaan', 'default.jpg', '2015-06-11 09:17:28', NULL, 0, 0),
(3, 'admin', 'me@home.net', '$2y$10$sYHxetsCWr6W0hyRh1aaxeQoDC39O3IrcEwvxdGVhQEBz/3R7wjBm', 'Admin GPIB', 'default.jpg', '2015-06-11 09:32:16', NULL, 1, 1);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
