-- phpMyAdmin SQL Dump
-- version 4.2.11
-- http://www.phpmyadmin.net
--
-- Host: 127.0.0.1
-- Generation Time: Jun 18, 2015 at 09:09 AM
-- Server version: 5.6.21
-- PHP Version: 5.6.3

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `gpib`
--
CREATE DATABASE IF NOT EXISTS `gpib` DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;
USE `gpib`;

-- --------------------------------------------------------

--
-- Table structure for table `ci_sessions`
--

DROP TABLE IF EXISTS `ci_sessions`;
CREATE TABLE IF NOT EXISTS `ci_sessions` (
  `id` varchar(40) NOT NULL,
  `ip_address` varchar(45) NOT NULL,
  `timestamp` int(10) unsigned NOT NULL DEFAULT '0',
  `data` blob NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- --------------------------------------------------------

--
-- Table structure for table `tbl_berita`
--

DROP TABLE IF EXISTS `tbl_berita`;
CREATE TABLE IF NOT EXISTS `tbl_berita` (
`id` int(11) NOT NULL,
  `cat_id` int(11) NOT NULL,
  `title` varchar(255) NOT NULL,
  `slug` varchar(255) NOT NULL,
  `desk` text NOT NULL,
  `author` varchar(255) NOT NULL,
  `create_by` int(11) NOT NULL,
  `update_by` int(11) NOT NULL,
  `create_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `update_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB AUTO_INCREMENT=21 DEFAULT CHARSET=latin1;

--
-- Dumping data for table `tbl_berita`
--

INSERT INTO `tbl_berita` (`id`, `cat_id`, `title`, `slug`, `desk`, `author`, `create_by`, `update_by`, `create_at`, `update_at`) VALUES
(3, 1, 'There is no one who loves pain itself', 'there-is-no-one-who-loves-pain-itself', '<p><strong><img alt="" src="/CI/uploads/images/63993_786773721388907_4086578249005417420_n.jpg" style="float:left; height:360px; width:480px" />Lorem Ipsum</strong>&nbsp;is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry&#39;s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum</p>\r\n', '', 1, 3, '2015-06-07 22:29:54', '2015-06-17 05:08:18'),
(4, 9, 'Query Builder Class', 'query-builder-class', '<p>CodeIgniter gives you access to a Query Builder class. This pattern allows information to be retrieved, inserted, and updated in your database with minimal scripting. In some cases only one or two lines of code are necessary to perform a database action. CodeIgniter does not require that each database table be its own class file. It instead provides a more simplified interface.</p>\r\n\r\n<p>Beyond simplicity, a major benefit to using the Query Builder features is that it allows you to create database independent applications, since the query syntax is generated by each database adapter. It also allows for safer queries, since the values are escaped automatically by the system.</p>\r\n', '', 1, 0, '2015-06-08 03:27:43', '2015-06-08 08:27:43'),
(5, 11, 'Pembukaan Bulan Pelkes (dulu disebut Pekabaran Injil)', 'pembukaan-bulan-pelkes-dulu-disebut-pekabaran-injil', '<p>Pada awalnya istilah Pekabaran Injil (PI) dianggap netral, artinya tidak menimbulkan salah interpretasi dalam hubungan antar umat beragama di Indonesia. Namun, sejak tahun 70-an. Istilah PI mulai menimbulkan rasa curiga dan apriori dari pihak umat Muslim terhadap praktek dan kegiatan misi Kristiani di Indonesia. Kemudian, istilah PI dikaitkan dengan usaha Kristenisasi atau memaksa umat lain untuk menjadi Kristen. Umat Kristen dituduh menyebarkan agama dengan cara paksa atau membujuk dengan memberikan bantuan agar orang yang dibantu beralih dari agamanya yang semula menjadi Kristen.</p>\r\n\r\n<p>Tanpa bermaksud untuk menghilangkan istilah PI yang sudah baku digunakan gereja-gereja di Indonesia. GPIB menggunakan dan mempopulerkan Istilah Pelayanan dan Kesaksian (Pelkes). Pelkes merupakan 2 aspek dari tridharma gereja (persekutuan, pelayanan) dan kesaksian, sekaligus pengejawantahan maksud istilah PI tersebut.</p>\r\n\r\n<p>Dalam kembara perjalanan Pelkes tersebut, kasih Tuhan selalu dinyatakan. Menapaki hari-hari pemberian Tuhan dengan keyakinan penuh bahwa Ia selalu beserta. Bertumbuh, berkembang dan berproses ditengah jemaat Tuhan, merupakan berkat terindah. Kini dan disini, seorang hamba dibentuk untuk melayani dengan ketulusan, kejujuran dan kerendahan hati. Sejenak menoleh kebelakang untuk kembali menatap kedepan dan menjalani pelayanan ditempat yang baru hanya karena pertolongan Tuhan. Sungguh, semua hanya karena pertolongan Tuhan...</p>\r\n', 'Pendeta Ny. Maria Y. Silahooij,S.Th,M.Pd.K', 1, 0, '2015-06-11 23:47:35', '2015-06-12 04:47:35'),
(6, 14, 'Memaknai Peristiwa Pentakosta', 'memaknai-peristiwa-pentakosta', '<p>&quot;Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.&quot;</p>\r\n', '', 3, 0, '2015-06-12 22:28:01', '2015-06-13 15:28:01'),
(8, 4, 'Barangsiapa Takut ia Tidak Sempurna', 'barangsiapa-takut-ia-tidak-sempurna', '<p>&quot;Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.&quot;</p>\r\n', '', 3, 0, '2015-06-12 22:37:29', '2015-06-13 15:37:29'),
(9, 6, 'Selamat Berbahagia Irian Simanjuntak & Steven Chen', 'selamat-berbahagia-irian-simanjuntak-steven-chen', '<p>&quot;Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.&quot;</p>\r\n', '', 3, 0, '2015-06-12 23:10:03', '2015-06-13 16:10:03'),
(10, 6, 'Turut Berbahagia Atas Menikahnya Sdri Amanda Sari', 'turut-berbahagia-atas-menikahnya-sdri-amanda-sari', '<p>&quot;Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.&quot;</p>\r\n', '', 3, 0, '2015-06-12 23:10:41', '2015-06-13 16:10:41'),
(11, 8, 'Dibutuhkan Tenaga Mechanical Engineering', 'dibutuhkan-tenaga-mechanical-engineering', '<p>&quot;Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.&quot;</p>\r\n', '', 3, 0, '2015-06-12 23:18:44', '2015-06-13 16:18:44'),
(12, 8, 'Dibutuhkan Tenaga Pengajar Pada Sekolah Kristen Budi Murni', 'dibutuhkan-tenaga-pengajar-pada-sekolah-kristen-budi-murni', '<p>&quot;Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.&quot;</p>\r\n', '', 3, 0, '2015-06-12 23:19:19', '2015-06-13 16:19:19'),
(13, 7, 'Mohon Didoakan Keluarga Bpk Sihite', 'mohon-didoakan-keluarga-bpk-sihite', '<p>&quot;Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.&quot;</p>\r\n', '', 3, 0, '2015-06-12 23:26:14', '2015-06-13 16:26:14'),
(14, 7, 'Terbaring Sakit Sdri Joelina Marisa Simatupang', 'terbaring-sakit-sdri-joelina-marisa-simatupang', '<p>&quot;Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.&quot;</p>\\r\\n', '', 3, 3, '2015-06-12 23:27:06', '2015-06-13 16:27:24'),
(15, 15, 'Pelantikan Pengurus Muda-Mudi', 'pelantikan-pengurus-muda-mudi', '<p>&quot;Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.&quot;</p>\r\n', '', 3, 0, '2015-06-12 23:45:27', '2015-06-13 16:45:27'),
(16, 15, 'Bakti Sosial', 'bakti-sosial', '<p>&quot;Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.&quot;</p>\r\n', '', 3, 0, '2015-06-12 23:52:51', '2015-06-13 16:52:51'),
(17, 16, 'Kunjungan Ke Panti Asuhan', 'kunjungan-ke-panti-asuhan', '<p>&quot;Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.&quot;</p>\r\n', '', 3, 0, '2015-06-12 23:54:16', '2015-06-13 16:54:16'),
(18, 12, 'Walking in the footsteps of faith', 'walking-in-the-footsteps-of-faith', '<p>&quot;Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.&quot;</p>\\r\\n\\r\\n<p>&nbsp;</p>\\r\\n\\r\\n<p>Sabda Bina Umat: Renungan SBU Pagi 2015<br />\\r\\n&nbsp;</p>\\r\\n\\r\\n<p>&nbsp;</p>\\r\\n', '', 3, 3, '2015-06-13 00:40:33', '2015-06-13 17:42:18'),
(19, 12, 'Terus Menerus Dibarui Roh Kudus', 'terus-menerus-dibarui-roh-kudus', '<p>&quot;Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.&quot;</p>\\r\\n\\r\\n<p>&nbsp;</p>\\r\\n\\r\\n<p>Sabda Bina Umat: Renungan SBU Pagi 2015</p>\\r\\n', '', 3, 3, '2015-06-13 00:41:20', '2015-06-13 17:42:26'),
(20, 12, 'Menyukacitakan Roh Kudus', 'menyukacitakan-roh-kudus', '<p>&quot;Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.&quot;</p>\\r\\n', '', 3, 3, '2015-06-13 00:41:39', '2015-06-13 17:58:57');

-- --------------------------------------------------------

--
-- Table structure for table `tbl_category`
--

DROP TABLE IF EXISTS `tbl_category`;
CREATE TABLE IF NOT EXISTS `tbl_category` (
`id` int(11) NOT NULL,
  `title` varchar(255) NOT NULL,
  `slug` varchar(255) NOT NULL,
  `desk` text NOT NULL,
  `parent_id` int(11) NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=18 DEFAULT CHARSET=latin1;

--
-- Dumping data for table `tbl_category`
--

INSERT INTO `tbl_category` (`id`, `title`, `slug`, `desk`, `parent_id`) VALUES
(1, 'Catatan dari Meja Pendeta', 'catatan-dari-meja-pendeta', 'Catatan dari Meja Pendeta', 0),
(3, 'Sejarah', 'sejarah', '', 1),
(4, 'Informasi Sekretariat', 'informasi-sekretariat', 'Informasi Sekretariat', 0),
(5, 'Berita GPIB Immanuel Pekanbaru', 'berita-gpib-immanuel-pekanbaru', 'Berita GPIB Immanuel Pekanbaru', 0),
(6, 'Pemberkatan Pernikahan', 'pemberkatan-pernikahan', 'Pemberkatan Pernikahan', 5),
(7, 'Jemaat Sakit', 'jemaat-sakit', 'Jemaat Sakit', 5),
(8, 'Lowongan Kerja', 'lowongan-kerja', 'Lowongan Kerja', 5),
(9, 'Materi / Download', 'materi-download', 'Materi / Download', 5),
(10, 'Berita Gereja dan Dunia', 'berita-gereja-dan-dunia', 'Berita Gereja dan Dunia', 0),
(11, 'SMS Dari Pendeta', 'sms-dari-pendeta', '', 0),
(12, 'Renungan SBU Pagi', 'renungan-sbu-pagi', '', 0),
(13, 'Renungan SBU Malam', 'renungan-sbu-malam', '', 0),
(14, 'Berita Majelis Sinode GPIB', 'berita-majelis-sinode-gpib', 'berita majelis sinode GPIB', 0),
(15, 'Event', 'event', 'event dan kegiatan penting lainnya', 0),
(16, 'Kegiatan Lainnya', 'kegiatan-lainnya', 'kegiatan penting lainnya', 0);

-- --------------------------------------------------------

--
-- Table structure for table `tbl_jemaat`
--

DROP TABLE IF EXISTS `tbl_jemaat`;
CREATE TABLE IF NOT EXISTS `tbl_jemaat` (
`id` int(11) NOT NULL,
  `f_name` varchar(20) NOT NULL,
  `m_name` varchar(20) NOT NULL,
  `l_name` varchar(20) NOT NULL,
  `gender` enum('LK','PR') NOT NULL,
  `dob` date NOT NULL DEFAULT '0000-00-00',
  `nikah` int(2) NOT NULL,
  `telp` varchar(20) DEFAULT NULL,
  `alamat` text NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=168 DEFAULT CHARSET=utf8;

--
-- Dumping data for table `tbl_jemaat`
--

INSERT INTO `tbl_jemaat` (`id`, `f_name`, `m_name`, `l_name`, `gender`, `dob`, `nikah`, `telp`, `alamat`) VALUES
(1, 'AKWILA ', 'REKKY PETRUS ', 'DAMANIK', 'LK', '1982-03-23', 1, '0761-36171', 'JL. BUNGA HARUM NO. 4  SUKAJADI HARJOSARI'),
(2, 'ROMAULI', '', '', 'PR', '0000-00-00', 1, '', 'JL. BUNGA HARUM NO. 4  SUKAJADI HARJOSARI'),
(3, 'KEREN ', 'PRISKILA', 'DAMANIK', 'PR', '2012-12-29', 0, '', 'JL. BUNGA HARUM NO. 4  SUKAJADI HARJOSARI'),
(4, 'ABEL ', 'ROLAND ', 'GULTOM', 'LK', '1972-09-08', 1, '0761-28123', 'JL. ABABIL NIO. 15A  SUKAJADI KAMPUNG MELAYU'),
(5, 'YULYATI', 'CHRISTIAN', 'ARUAN', 'PR', '1971-07-31', 1, '', 'JL. ABABIL NIO. 15A  SUKAJADI KAMPUNG MELAYU'),
(6, 'MATTHEW P. C', 'NATHANEL', 'GULTOM', 'LK', '2000-06-12', 0, '', 'JL. ABABIL NIO. 15A  SUKAJADI KAMPUNG MELAYU'),
(7, 'DAVID', 'CLEO', 'GULTOM', 'LK', '2003-01-29', 0, '', 'JL. ABABIL NIO. 15A  SUKAJADI KAMPUNG MELAYU'),
(8, 'TIMOTHY', 'CLEYTUS', 'GULTOM', 'LK', '2003-01-29', 0, '', 'JL. ABABIL NIO. 15A  SUKAJADI KAMPUNG MELAYU'),
(9, 'AKTOR ', 'JUANG ', 'LAOWO', 'LK', '1988-08-31', 0, '', 'JL. AHMAD DAHLAN NO. 125  SUKAJADI '),
(10, 'GUSWITA', '', 'LAOWO', 'PR', '1986-08-09', 0, '', 'JL. AHMAD DAHLAN NO. 125  SUKAJADI '),
(11, 'VICTOR', '', 'LAOWO', 'LK', '1985-05-27', 0, '', 'JL. AHMAD DAHLAN NO. 125  SUKAJADI '),
(12, 'AMES ', 'RESMAN ', 'DAMANIK', 'LK', '1946-12-28', 0, '0761-36171', 'JL. BUNGA HARUM NO. 4  SUKAJADI HARJOSARI'),
(13, 'NURLINA', '', 'SARAGIH', 'PR', '1950-12-20', 0, '', 'JL. BUNGA HARUM NO. 4  SUKAJADI HARJOSARI'),
(14, 'ANDREW ', 'RIGGS WILSON ', 'DAMANIK', 'LK', '1978-02-12', 0, '0761-36171', 'JL. BUNGA HARUM NO. 4  SUKAJADI HARJOSARI'),
(15, 'RIO', 'MARLINA ', 'PANJAITAN', 'PR', '0000-00-00', 0, '', 'JL. BUNGA HARUM NO. 4  SUKAJADI HARJOSARI'),
(16, 'ANUGERAH', 'PASKAH', 'DAMANIK', 'LK', '0000-00-00', 0, '', 'JL. BUNGA HARUM NO. 4  SUKAJADI HARJOSARI'),
(17, 'APREDING ', '', 'TANDIRURA', 'LK', '1972-11-28', 1, '', 'ASRAMA BRIMOB BLOK F NO. 3 SUKAJADI -KAMPUNG MELAYU'),
(18, 'ERNY ', 'SOFICE TULLE', '', 'PR', '1980-05-02', 1, '', 'ASRAMA BRIMOB BLOK F NO. 3 SUKAJADI -KAMPUNG MELAYU'),
(19, 'JERREMY . A', '', 'TANDIRURA', 'LK', '2001-05-24', 0, '', 'ASRAMA BRIMOB BLOK F NO. 3 SUKAJADI -KAMPUNG MELAYU'),
(20, 'SAHRANY C.F', '', 'TANDIRURA', 'PR', '2005-02-27', 0, '', 'ASRAMA BRIMOB BLOK F NO. 3 SUKAJADI -KAMPUNG MELAYU'),
(21, 'BUDHI ', 'PRASETYO ', 'KORENGKENG', 'LK', '1973-10-11', 0, '0761-46459', 'JL. DURIAN NO. 3  SUKAJADI JADIREJO'),
(22, 'SEPTINA ', 'MARYANTI', 'SIMANJUNTAK', 'PR', '1975-09-23', 0, '', 'JL. DURIAN NO. 3  SUKAJADI JADIREJO'),
(23, 'DAVID ', 'YUNIKO ', 'SILITONGA', 'LK', '1977-06-11', 0, '0761-41287', 'JL. KH AHMAD DAHLAN NO. 85B RUKO SUKAJADI KAMPUNG TENGAH'),
(24, 'RETNO ', 'INDRAWATI', 'SINGGIH', 'PR', '1979-02-28', 0, '', 'JL. KH AHMAD DAHLAN NO. 85B RUKO SUKAJADI KAMPUNG TENGAH'),
(25, 'DJOKO ', '', 'SETIABOEDI', 'LK', '1955-09-02', 0, '', 'JL. DURIAN GG. PEPAYA I NO. 42A  PERUMAHAN SUKAJADI PULAU KARAM'),
(26, 'YOHANDRES', '', 'LIDYA', 'PR', '1965-09-12', 0, '', 'JL. DURIAN GG. PEPAYA I NO. 42A  PERUMAHAN SUKAJADI PULAU KARAM'),
(27, 'JODEA ANGGER', 'MOSESSA', '', 'LK', '1987-06-10', 0, '', 'JL. DURIAN GG. PEPAYA I NO. 42A  PERUMAHAN SUKAJADI PULAU KARAM'),
(28, 'JOSUA GILANG', 'YOSE SOGHANA', '', 'LK', '1993-04-26', 0, '', 'JL. DURIAN GG. PEPAYA I NO. 42A  PERUMAHAN SUKAJADI PULAU KARAM'),
(29, 'JOARES LANGGENG', 'TEGARA', '', 'LK', '1999-07-23', 0, '', 'JL. DURIAN GG. PEPAYA I NO. 42A  PERUMAHAN SUKAJADI PULAU KARAM'),
(30, 'FIRMAN MARULI ', 'HAMONANGAN ', 'PANDIANGAN', 'LK', '1953-09-13', 0, '0761-20097', 'JL. ANGKASA NO. 9  PAYUNG SEKAKI AIR HITAM'),
(31, 'ANI', 'NOVITA', 'SURBAKTI', 'PR', '1959-09-04', 0, '', 'JL. ANGKASA NO. 9  PAYUNG SEKAKI AIR HITAM'),
(32, 'BENNY DWI', 'PUTRA', 'PANDIANGAN', 'LK', '1990-06-21', 0, '', 'JL. ANGKASA NO. 9  PAYUNG SEKAKI AIR HITAM'),
(33, 'DEBOY CHRISTINA', 'NATALIA', 'PANDIANGAN', 'PR', '1995-12-06', 0, '', 'JL. ANGKASA NO. 9  PAYUNG SEKAKI AIR HITAM'),
(34, 'THOMAS PAREL', 'HERMAWAN', 'PANDIANGAN', 'LK', '1983-02-09', 0, '', 'JL. ANGKASA NO. 9  PAYUNG SEKAKI AIR HITAM'),
(35, 'FIRMAN ', '', 'MARPAUNG', 'LK', '1941-09-18', 0, '', 'JL. KUTILANG NO. 25  SUKAJADI KAMPUNG MELAYU'),
(36, 'ROSMIATI', '', 'SIAHAAN', 'PR', '1954-12-27', 0, '', 'JL. KUTILANG NO. 25  SUKAJADI KAMPUNG MELAYU'),
(37, 'HENDRI ', '', 'LAHEBA', 'LK', '1959-11-11', 0, '0761-36043', 'JL. MELUR GG. AL-JIHAD NO. 9  SUKAJADI KEDUNG SARI'),
(38, 'ITA ', 'AGUSTINI', 'SUKATIYO', 'PR', '1966-08-20', 0, '', 'JL. MELUR GG. AL-JIHAD NO. 9  SUKAJADI KEDUNG SARI'),
(39, 'TIMOTHY ', 'REY', 'LAHEBA', 'LK', '1991-03-20', 0, '', 'JL. MELUR GG. AL-JIHAD NO. 9  SUKAJADI KEDUNG SARI'),
(40, 'TEOFILUS', 'HANS', 'LAHEBA', 'LK', '1992-04-14', 0, '', 'JL. MELUR GG. AL-JIHAD NO. 9  SUKAJADI KEDUNG SARI'),
(41, 'HERRY ', 'RAMON ', 'PANJAITAN', 'LK', '1969-11-30', 0, '0761-885530', 'JL. KH AHMAD DAHLAN GG. KELINCI NO. 46 SUKAJADI HARJOSARI'),
(42, 'CAROLINA', '', 'SIMAMORA', 'PR', '1970-09-29', 0, '', 'JL. KH AHMAD DAHLAN GG. KELINCI NO. 46 SUKAJADI HARJOSARI'),
(43, 'MANOAH', 'SOALOAN', 'PANJAITAN', 'LK', '2003-10-29', 0, '', 'JL. KH AHMAD DAHLAN GG. KELINCI NO. 46 SUKAJADI HARJOSARI'),
(44, 'DOMININGUS', 'NATALIA', 'PANJAITAN', 'LK', '2008-02-09', 0, '', 'JL. KH AHMAD DAHLAN GG. KELINCI NO. 46 SUKAJADI HARJOSARI'),
(45, 'VINCENT', '', 'PANJAITAN', 'LK', '2009-11-22', 0, '', 'JL. KH AHMAD DAHLAN GG. KELINCI NO. 46 SUKAJADI HARJOSARI'),
(46, 'HOTMA ', 'PARULIAN ', 'SITOHANG', 'LK', '1967-02-04', 0, '0761-23554', 'JL. MELUR UJUNG/NENAS NO.15  SENAPELAN PADANG TERUBUK'),
(47, 'NANI', 'MAGDALENA', 'NAPITUPULU', 'PR', '1970-07-06', 0, '', 'JL. MELUR UJUNG/NENAS NO.15  SENAPELAN PADANG TERUBUK'),
(48, 'GITA SHERLY', 'FEBIOLA', 'SITOHANG', 'PR', '2004-05-13', 0, '', 'JL. MELUR UJUNG/NENAS NO.15  SENAPELAN PADANG TERUBUK'),
(49, 'GAVRILA ', 'ANGELA KESIA', 'SITOHANG', 'PR', '2000-05-10', 0, '', 'JL. MELUR UJUNG/NENAS NO.15  SENAPELAN PADANG TERUBUK'),
(50, 'JEMRIF ', 'ED ', 'BANUNAEK', 'LK', '1975-05-01', 0, '', 'JL. RUSA NO. 7  SUKAJADI HARJOSARI'),
(51, 'DONNA ', 'RN', 'BARIMBING', 'PR', '1984-12-13', 0, '', 'JL. RUSA NO. 7  SUKAJADI HARJOSARI'),
(52, 'FREDERICO ', '', 'BANUNAEK', 'LK', '2010-09-27', 0, '', 'JL. RUSA NO. 7  SUKAJADI HARJOSARI'),
(53, 'YUDA ', '', 'PATILAWA', 'LK', '1971-08-01', 0, '', 'JL. DURIAN/PEPAYA NO. 1  PULAU KARAM SUKAJADI'),
(54, 'YOSEF LUKU', 'PRASETYO', '', 'LK', '1980-10-09', 0, '', 'JL. DURIAN/PEPAYA NO. 1  PULAU KARAM SUKAJADI'),
(55, 'JOHADI ', '', 'JOKANAN', 'LK', '1937-07-03', 0, '0761-25890', 'JL. DURIAN GG. PEPAYA I NO. 42 A  SUKAJADI PULAU KARAM'),
(56, 'YENTI CAROLINA', 'YOSEPHA', '', 'PR', '1980-08-30', 0, '', 'JL. DURIAN/PEPAYA NO. 1  PULAU KARAM SUKAJADI'),
(57, 'JOSIAS ', 'MARTONO ', 'TAKDARE', 'LK', '1947-05-31', 0, '0761-29530', 'JL. CEMPAKA GG. SURYA 1 NO. 28 A  SUKAJADI SUKAJADI'),
(58, 'TIAPUL', 'MAGDALENA', 'HUTABARAT', 'PR', '1950-12-05', 0, '', 'JL. CEMPAKA GG. SURYA 1 NO. 28 A  SUKAJADI SUKAJADI'),
(59, 'ANDREAS', 'BENHAR NUGROHO', 'TAKDARE', 'LK', '1977-10-04', 0, '', 'JL. CEMPAKA GG. SURYA 1 NO. 28 A  SUKAJADI SUKAJADI'),
(60, 'ANITA', 'JOSEPHINE SETIATI', 'TAKDARE', 'PR', '1979-03-14', 0, '', 'JL. CEMPAKA GG. SURYA 1 NO. 28 A  SUKAJADI SUKAJADI'),
(61, 'ALICE', 'MARGARETTA', 'TAKDARE', 'PR', '1983-05-20', 0, '', 'JL. CEMPAKA GG. SURYA 1 NO. 28 A  SUKAJADI SUKAJADI'),
(62, 'KASMANTA ', '', 'SINURAYA', 'LK', '1942-05-10', 0, '', 'JL. MELUR UJUNG/NENAS NO. 6B  SENAPELAN PADANG TERUBUK'),
(63, 'KASMIATI', '', 'GINTING', 'PR', '1947-11-22', 0, '', 'JL. MELUR UJUNG/NENAS NO. 6B  SENAPELAN PADANG TERUBUK'),
(64, 'JERRY', 'MEDIANTO', 'SINURAYA', 'LK', '1970-07-05', 0, '', 'JL. MELUR UJUNG/NENAS NO. 6B  SENAPELAN PADANG TERUBUK'),
(65, 'YUNIARTO', '', 'SINURAYA', 'LK', '1971-07-26', 0, '', 'JL. MELUR UJUNG/NENAS NO. 6B  SENAPELAN PADANG TERUBUK'),
(66, 'YAN ', 'MANNA PUTRA', 'SINURAYA', 'LK', '0000-00-00', 0, '', 'JL. MELUR UJUNG/NENAS NO. 6B  SENAPELAN PADANG TERUBUK'),
(67, 'MANAOR ', '', 'SIAHAAN', 'LK', '1939-08-19', 1, '0761-22442', 'JL. PEPAYA NO. 13  SUKAJADI PULO KARAM'),
(68, 'TIORIA', '', 'SIANIPAR', 'PR', '1945-08-17', 1, '', 'JL. PEPAYA NO. 13  SUKAJADI PULO KARAM'),
(69, 'MANGAPUL ', '', 'NAINGGOLAN', 'LK', '1978-05-12', 0, '', 'JL. RUSA NO. 14  SUKAJADI HARJOSARI'),
(70, 'DEBY', 'NURSANTI', 'MANALU', 'PR', '1980-03-20', 0, '', 'JL. RUSA NO. 14  SUKAJADI HARJOSARI'),
(71, 'DESY', 'KANIA', 'NAINGGOLAN', 'PR', '2005-12-01', 0, '', 'JL. RUSA NO. 14  SUKAJADI HARJOSARI'),
(72, 'CISILLIA ', 'REGINA', 'NAINGGOLAN', 'PR', '2007-06-16', 0, '', 'JL. RUSA NO. 14  SUKAJADI HARJOSARI'),
(73, 'MAX ', 'ROBERT ', 'RUMENGAN', 'LK', '1959-11-24', 0, '0761-861320', 'JL. NANGKA GG. HOP NO.7 SUKAJADI KAMPUNG MELAYU'),
(74, 'KRISTIYANTI', 'LAURICA ', 'SIAGIAN', 'PR', '1969-11-05', 0, '', 'JL. NANGKA GG. HOP NO.7 SUKAJADI KAMPUNG MELAYU'),
(75, 'RIKO', 'FEBRIAN', 'RUMENGAN', 'LK', '2002-02-23', 0, '', 'JL. NANGKA GG. HOP NO.7 SUKAJADI KAMPUNG MELAYU'),
(76, 'MELKY ', 'GUSLOW ', 'BANUNAEK', 'LK', '1979-09-12', 0, '', 'JL. RUSA NO. 9  SUKAJADI HARJOSARI'),
(77, 'NOVENTY', 'SETYANINGSIH', '', 'PR', '1978-11-19', 0, '', 'JL. RUSA NO. 9  SUKAJADI HARJOSARI'),
(78, 'JESSICA', 'DERVIANA', 'BANUNAEK', 'PR', '2008-11-01', 0, '', 'JL. RUSA NO. 9  SUKAJADI HARJOSARI'),
(79, 'CECILLIA', 'AYUWARDANI', 'BANUNAEK', 'PR', '2008-11-01', 0, '', 'JL. RUSA NO. 9  SUKAJADI HARJOSARI'),
(80, 'CHRISTIAN', 'GRADY', 'BANUNAEK', 'LK', '2012-11-14', 0, '', 'JL. RUSA NO. 9  SUKAJADI HARJOSARI'),
(81, 'SERLI', 'MAYA', 'TAMELAN', 'PR', '1989-07-03', 0, '', 'JL. RUSA NO. 9  SUKAJADI HARJOSARI'),
(82, 'SOLEMAN', '', 'SEO', 'LK', '1992-08-10', 0, '', 'JL. RUSA NO. 9  SUKAJADI HARJOSARI'),
(83, 'IMER', 'SAFET', 'TAMELAN', 'LK', '1990-03-01', 0, '', 'JL. RUSA NO. 9  SUKAJADI HARJOSARI'),
(84, 'MIKAEL ', '', 'SAMOSIR', 'LK', '1963-10-12', 0, '', 'JL. MUTIARA NO. 22  SENAPELAN PADANG TERUBUK'),
(85, 'MONICA ', 'LINDA', 'NAIBAHO', 'PR', '1957-01-20', 0, '', 'JL. MUTIARA NO. 22  SENAPELAN PADANG TERUBUK'),
(86, 'CHRISTINE', 'HELMY MONALISA', 'SAMOSIR', 'PR', '1996-09-09', 0, '', 'JL. MUTIARA NO. 22  SENAPELAN PADANG TERUBUK'),
(87, 'MIROS ', '', 'SINURAYA', 'LK', '1948-12-31', 0, '0761-38867', 'JL. DAHLIA GG. PMI NO. 47A  SUKAJADI REJOSARI'),
(88, 'MIKE', '', 'SINURAYA', 'LK', '1978-06-08', 0, '', 'JL. DAHLIA GG. PMI NO. 47A  SUKAJADI REJOSARI'),
(89, 'MULAWAN ', '', 'HUTAGAOL', 'LK', '1965-07-27', 0, '0761-42440', 'JL. MUTIARA NO. 4  SENAPELAN PADANG TERUBUK'),
(90, 'ROSWATI', '', 'NAPITUPULU', 'PR', '1964-04-17', 0, '', 'JL. MUTIARA NO. 4  SENAPELAN PADANG TERUBUK'),
(91, 'TANTI', 'MULIATI', 'HUTAGAOL', 'PR', '1996-01-22', 0, '', 'JL. MUTIARA NO. 4  SENAPELAN PADANG TERUBUK'),
(92, 'LEO', 'TAN SAPUTRA', 'HUTAGAOL', 'LK', '1998-07-30', 0, '', 'JL. MUTIARA NO. 4  SENAPELAN PADANG TERUBUK'),
(93, 'DAMERIA', '', '', 'PR', '1972-06-13', 0, '', 'JL. KAMBOJA GG. PURA CENDANA NO. 17  SUKAJADI SUKAJADI'),
(94, 'NATALIA', '', '', 'PR', '1995-12-09', 0, '', 'JL. KAMBOJA GG. PURA CENDANA NO. 17  SUKAJADI SUKAJADI'),
(95, 'MURNIATI ', '', 'HUTABARAT', 'PR', '1942-08-01', 0, '0761-47784', 'JL. KAMBOJA GG. PURA CENDANA NO. 17  SUKAJADI SUKAJADI'),
(96, 'NIKOLAUS ', '', 'SINAY', 'LK', '1963-11-01', 1, '0761-848854', 'JL. CEMPAKA GG. SURYA I NO. 28B  SUKAJADI SUKAJADI'),
(97, 'ESTERLINA ', 'ALENDALINA ', 'SINAY', 'PR', '1971-04-06', 1, '', 'JL. CEMPAKA GG. SURYA I NO. 28B  SUKAJADI SUKAJADI'),
(98, 'STANY', 'GRACE', 'SINAY', 'PR', '1989-10-05', 0, '', 'JL. CEMPAKA GG. SURYA I NO. 28B  SUKAJADI SUKAJADI'),
(99, 'FIORELLO', 'NEVAN', 'SINAY', 'LK', '2011-03-24', 0, '', 'JL. CEMPAKA GG. SURYA I NO. 28B  SUKAJADI SUKAJADI'),
(100, 'ANNABELLE', 'SHARON', 'SINAY', 'PR', '2012-12-15', 0, '', 'JL. CEMPAKA GG. SURYA I NO. 28B  SUKAJADI SUKAJADI'),
(101, 'DIANA ', 'ISYELONE ', 'MUSKITTA', 'PR', '1979-09-14', 0, '', 'JL. CEMPAKA GG. SURYA I NO. 28B  SUKAJADI SUKAJADI'),
(102, 'MARLEN', '', 'SINAY', 'PR', '1977-03-18', 0, '', 'JL. CEMPAKA GG. SURYA I NO. 28B  SUKAJADI SUKAJADI'),
(103, 'NYOMAN ', 'SUAMBA YASA', '', 'LK', '1955-10-24', 0, '0761-22919', 'JL. TERATAI GG. BUNGA RAYA NO. 97  SENAPELAN PADANG TERUBUK'),
(104, 'RATNA', 'MEGAWATI', '', 'PR', '1958-01-22', 0, '', 'JL. TERATAI GG. BUNGA RAYA NO. 97  SENAPELAN PADANG TERUBUK'),
(105, 'SHERIN', 'ROSALIA', '', 'PR', '1999-08-18', 0, '', 'JL. TERATAI GG. BUNGA RAYA NO. 97  SENAPELAN PADANG TERUBUK'),
(106, 'PANGIHUTAN ', '', 'SITUMORANG', 'LK', '1958-11-15', 0, '', 'JL. BALAM GG. PUYUH  SUKAJADI KAMPUNG MELAYU'),
(107, 'HELMY', 'DIANA', '', 'PR', '1963-07-09', 0, '', 'JL. BALAM GG. PUYUH  SUKAJADI KAMPUNG MELAYU'),
(108, 'MURNI', 'IRMAWATI', '', 'PR', '1984-08-07', 0, '', 'JL. BALAM GG. PUYUH  SUKAJADI KAMPUNG MELAYU'),
(109, 'RICKY', 'LEONARDO', '', 'LK', '1985-10-24', 0, '', 'JL. BALAM GG. PUYUH  SUKAJADI KAMPUNG MELAYU'),
(110, 'YOSUA', 'ANDREAS', '', 'LK', '1994-04-14', 0, '', 'JL. BALAM GG. PUYUH  SUKAJADI KAMPUNG MELAYU'),
(111, 'RICHARD ', '', 'PANJAITAN', 'LK', '1940-05-10', 0, '', 'JL. KH. AHMAD DAHLAN GG. KELINCI NO. 46  SUKAJADI HARJOSARI'),
(112, 'ROBIN ', '', 'HUTAGALUNG', 'LK', '1963-09-07', 0, '0761-22309', 'JL. KETITIRAN NO. 10  SUKAJADI KAMPUNG MELAYU'),
(113, 'SUWANTI', '', '', 'PR', '1974-07-13', 0, '', 'JL. KETITIRAN NO. 10  SUKAJADI KAMPUNG MELAYU'),
(114, 'ZELOT', 'AGRIFA', 'HUTAGALUNG', 'LK', '1995-04-29', 0, '', 'JL. KETITIRAN NO. 10  SUKAJADI KAMPUNG MELAYU'),
(115, 'DELLA', 'SARAFINA', 'HUTAGALUNG', 'PR', '1997-10-24', 0, '', 'JL. KETITIRAN NO. 10  SUKAJADI KAMPUNG MELAYU'),
(116, 'BRYAN', 'ZEFANYA', 'HUTAGALUNG', 'LK', '2002-07-10', 0, '', 'JL. KETITIRAN NO. 10  SUKAJADI KAMPUNG MELAYU'),
(117, 'SIDIRIA ', '', 'HURA', 'PR', '1967-07-05', 0, '', 'JL. DURIAN GG. KEDUNG SARI  NO. 30 G SUKAJADI KEDUNG SARI'),
(118, 'KURNIAWAN', '', 'HAREFA', 'LK', '1988-11-04', 0, '', 'JL. DURIAN GG. KEDUNG SARI  NO. 30 G SUKAJADI KEDUNG SARI'),
(119, 'DEDDY ', 'KRISTIAWAN', 'HAREFA', 'LK', '1992-03-12', 0, '', 'JL. DURIAN GG. KEDUNG SARI  NO. 30 G SUKAJADI KEDUNG SARI'),
(120, 'WIRA', 'PUTRA', 'HAREFA', 'LK', '1995-04-08', 0, '', 'JL. DURIAN GG. KEDUNG SARI  NO. 30 G SUKAJADI KEDUNG SARI'),
(121, 'SIMON ', 'SUHARTO', '', 'LK', '1966-08-27', 0, '0761-38304', 'JL. MELATI GG. ASTER NO. 18  HARJOSARI SUKAJADI'),
(122, 'WANTIN', 'ROSTINI', '', 'PR', '1965-04-30', 0, '', 'JL. MELATI GG. ASTER NO. 18  HARJOSARI SUKAJADI'),
(123, 'NUGROHO', '', '', 'LK', '1999-07-04', 0, '', 'JL. MELATI GG. ASTER NO. 18  HARJOSARI SUKAJADI'),
(124, 'PANJI', 'PANGESTU', '', 'LK', '1996-03-27', 0, '', 'JL. MELATI GG. ASTER NO. 18  HARJOSARI SUKAJADI'),
(125, 'CHAIA', 'CHRISTIE', '', 'PR', '2003-03-03', 0, '', 'JL. MELATI GG. ASTER NO. 18  HARJOSARI SUKAJADI'),
(126, 'SINGGIH ', '', 'ATMOSUTARJO', 'LK', '1946-08-06', 0, '0761-32810', 'JL. SELINDIT NO. 3  SUKAJADI KAMPUNG MELAYU'),
(127, 'TRI', 'PUTRIYATI', '', 'PR', '1951-03-18', 0, '', 'JL. SELINDIT NO. 3  SUKAJADI KAMPUNG MELAYU'),
(128, 'UTAMI', 'TRIE WAHYUNI', 'SINGGIH', 'PR', '1985-11-26', 0, '', 'JL. SELINDIT NO. 3  SUKAJADI KAMPUNG MELAYU'),
(129, 'SUDAR ', '', 'KALIONO', 'LK', '1937-01-28', 0, '0761-38304', 'JL. MELATI GG. ASTER NO. 18  HARJOSARI SUKAJADI'),
(130, 'MARTINI', '', 'BLEDOEG', 'PR', '1933-02-15', 0, '', 'JL. MELATI GG. ASTER NO. 18  HARJOSARI SUKAJADI'),
(131, 'YOSEF ', 'WIRATNO', '', 'LK', '1962-07-12', 0, '', 'JL. MELATI GG. ASTER NO. 18  HARJOSARI SUKAJADI'),
(132, 'HANDRIS ', '', 'TAMBOTO', 'LK', '1948-11-01', 0, '', 'JL. PUTRI NILAM GG. PUTRI HIJAU NO. 3A  SUKAJADI KAMPUNG TENGAH'),
(133, 'NURLINA', '', 'KAMINANG', 'PR', '1962-09-13', 0, '', 'JL. PUTRI NILAM GG. PUTRI HIJAU NO. 3A  SUKAJADI KAMPUNG TENGAH'),
(134, 'SURINI ', '', 'KAMINANG', 'PR', '1945-10-05', 0, '0761-46608', 'JL. PUTRI NILAM GG. PUTRI HIJAU NO. 3A  SUKAJADI KAMPUNG TENGAH'),
(135, 'TEGUH ', 'SETIYADI ', 'SOEDIBYO', 'LK', '1967-09-01', 0, '', 'JL. RUSA  SUKAJADI HARJOSARI'),
(136, 'RATNA', 'SARI', 'TINAMBUNAN', 'PR', '1971-05-05', 0, '', 'JL. RUSA  SUKAJADI HARJOSARI'),
(137, 'RANDY', 'ATMADJA', 'SETIYADI', 'LK', '1998-11-23', 0, '', 'JL. RUSA  SUKAJADI HARJOSARI'),
(138, 'PIETHA TIARA', 'LINGGA DEWI', 'SETIYADI', 'PR', '2000-03-20', 0, '', 'JL. RUSA  SUKAJADI HARJOSARI'),
(139, 'GRACESHELLA', 'TRI ANASYA', 'SETIYADI', 'PR', '2004-06-09', 0, '', 'JL. RUSA  SUKAJADI HARJOSARI'),
(140, 'TOEKIDJO ', 'HARDJO ', 'PAWIRO', 'LK', '1937-03-28', 0, '', 'JL. TULIP NO. 27  SUKAJADI HARJOSARI'),
(141, 'YUNIOR ', 'ELRICO ', 'MARPAUNG', 'LK', '1979-06-18', 0, '', 'JL. KUTILANG NO. 25  SUKAJADI KAMPUNG MELAYU'),
(142, 'IMELDA', 'SEVENT', 'HUTAHAEAN', 'PR', '1984-11-07', 0, '', 'JL. KUTILANG NO. 25  SUKAJADI KAMPUNG MELAYU'),
(143, 'GABRIEL', 'NATANAEL', 'MARPAUNG', 'LK', '2011-07-02', 0, '', 'JL. KUTILANG NO. 25  SUKAJADI KAMPUNG MELAYU'),
(144, 'CALVIN', 'YURICO MARCHELO', 'MARPAUNG', 'LK', '2014-01-08', 0, '', ''),
(145, 'ZULKIFLI ', 'ZAINUDIN', '', 'LK', '1968-03-07', 0, '', 'JL. KIJANG NO. 27 SUKAJADI'),
(146, 'OKTARIA', 'MEIKALINA', '', 'PR', '1967-10-23', 0, '', 'JL. KIJANG NO. 27 SUKAJADI'),
(147, 'ALEXANDER', 'JULIO', '', 'LK', '1998-07-06', 0, '', 'JL. KIJANG NO. 27 SUKAJADI'),
(148, 'LUSI', 'FEBRIANI', '', 'PR', '2000-02-08', 0, '', 'JL. KIJANG NO. 27 SUKAJADI'),
(149, 'RINI OKTARIANI', 'PUTRI', '', 'PR', '2004-10-25', 0, '', 'JL. KIJANG NO. 27 SUKAJADI'),
(150, 'KADARYONO', '', '', 'LK', '1961-11-02', 0, '0761-885629', 'JL. KUTILANG NO. 11, SUKAJADI KAMPUNG MELAYU'),
(151, 'KURNIA', 'SWITA ', 'SARAGIH', 'PR', '1965-05-12', 0, '', 'JL. KUTILANG NO. 11, SUKAJADI KAMPUNG MELAYU'),
(152, 'KINANTI', 'SHINTA ', 'DEBORA', 'PR', '1992-04-30', 0, '', 'JL. KUTILANG NO. 11, SUKAJADI KAMPUNG MELAYU'),
(153, 'KRISAN', 'FARRAETTY', '', 'PR', '1995-05-29', 0, '', 'JL. KUTILANG NO. 11, SUKAJADI KAMPUNG MELAYU'),
(154, 'KEVIN ', 'NOEL', 'ANUGERAH', 'LK', '1996-12-12', 0, '', 'JL. KUTILANG NO. 11, SUKAJADI KAMPUNG MELAYU'),
(155, 'KIM ', '', 'SUN', 'LK', '1979-08-17', 0, '', 'JL. ANGKASA GG. ANGKASA III UJUNG NO.   AIR HITAM PAYUNG SEKAKI'),
(156, 'SANDY', '', 'MANANGGEL', 'PR', '1976-05-28', 0, '', 'JL. ANGKASA GG. ANGKASA III UJUNG NO.   AIR HITAM PAYUNG SEKAKI'),
(157, 'VANESSA', 'SRINI GRACIA', '', 'PR', '1998-07-02', 0, '', 'JL. ANGKASA GG. ANGKASA III UJUNG NO.   AIR HITAM PAYUNG SEKAKI'),
(158, 'AGATHA', 'CRISTY GRACIA', '', 'PR', '2005-07-15', 0, '', 'JL. ANGKASA GG. ANGKASA III UJUNG NO.   AIR HITAM PAYUNG SEKAKI'),
(159, 'EGAN', 'IMANUEL KIMDY', '', 'LK', '2010-09-16', 0, '', 'JL. ANGKASA GG. ANGKASA III UJUNG NO.   AIR HITAM PAYUNG SEKAKI'),
(160, 'WELLY ', 'JAVANICA ', 'PANJAITAN', 'LK', '1981-08-01', 0, '', 'JL. KUTILANG NO. 32 SUKAJADI KAMPUNG MELAYU'),
(161, 'NATHASIA', 'MAUREEN', '', 'PR', '1984-12-03', 0, '', 'JL. KUTILANG NO. 32 SUKAJADI KAMPUNG MELAYU'),
(162, 'CHRISTIAN', 'JEREMY', 'PANJAITAN', 'LK', '2005-05-02', 0, '', 'JL. KUTILANG NO. 32 SUKAJADI KAMPUNG MELAYU'),
(163, 'KAYLA', 'ALLYSHA ELIZABETH', 'PANJAITAN', 'PR', '2006-12-05', 0, '', 'JL. KUTILANG NO. 32 SUKAJADI KAMPUNG MELAYU'),
(164, 'YOHANNA', 'AUDREY CALLISTA', 'PANJAITAN', 'PR', '2008-11-06', 0, '', 'JL. KUTILANG NO. 32 SUKAJADI KAMPUNG MELAYU'),
(165, 'DENOVMAN ', '', 'SINURAYA', 'LK', '1975-01-08', 0, '', 'JL. MELATI INDAH / BUNGA TANJUNG PERUM PONDOK RATU BLOK D NO. 4, DELIMA - TAMPAN'),
(166, 'YUNITA', 'DEWI', '', 'PR', '1984-09-17', 0, '', 'JL. MELATI INDAH / BUNGA TANJUNG PERUM PONDOK RATU BLOK D NO. 4, DELIMA - TAMPAN'),
(167, 'NOVITA', 'SARI', 'SINURAYA', 'PR', '2004-11-20', 0, '', 'JL. MELATI INDAH / BUNGA TANJUNG PERUM PONDOK RATU BLOK D NO. 4, DELIMA - TAMPAN');

-- --------------------------------------------------------

--
-- Table structure for table `tbl_kegiatan`
--

DROP TABLE IF EXISTS `tbl_kegiatan`;
CREATE TABLE IF NOT EXISTS `tbl_kegiatan` (
`id` int(11) NOT NULL,
  `kegiatan` varchar(255) NOT NULL,
  `tanggal` date NOT NULL DEFAULT '0000-00-00',
  `pukul` varchar(5) NOT NULL,
  `tempat` varchar(255) NOT NULL,
  `pemimpin` varchar(255) NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=30 DEFAULT CHARSET=latin1;

--
-- Dumping data for table `tbl_kegiatan`
--

INSERT INTO `tbl_kegiatan` (`id`, `kegiatan`, `tanggal`, `pukul`, `tempat`, `pemimpin`) VALUES
(1, ' Ibadah Keluarga Sektor1a:Kel. Sumilat', '2015-06-17', '19:30', ' Jl. Cendrawasih 2    ', 'Dkn Ny. Rita Gunawan'),
(2, ' Ibadah Keluarga Sektor1b:Kel. M.Pikarima', '2015-06-17', '19:30', '  Perum BKP Blok E 12 ', 'Pnt. W. Soempeno'),
(3, ' Ibadah Keluarga Sektor2abc:Kel. J. Jacobs', '2015-06-17', '19:30', ' Jl. Johar II C/ 210 ', 'Dkn Ny.V. Simorangkir'),
(4, ' Ibadah Keluarga Sektor2def:Kel. E.Matheus', '2015-06-17', '19:30', ' Jl. Randu Blok C ', 'Pnt. D.J. Rompis'),
(5, ' Ibadah Keluarga Sektor3a:Kel.Ny.U.Hetharia', '2015-06-17', '19:30', '  Jl.Jkt timur II Blok D11/ 16 ', 'Dkn Y. Budiyono T.S'),
(6, ' Ibadah Keluarga Sektor3b:Kel.B.Simanjuntak ', '2015-06-17', '19:30', ' Jl.Bekasi Permai BL - 28 ', 'Dkn Ny. L. Wenas'),
(7, ' Ibadah Keluarga Sektor4a:Kel.Andi Sugiarto', '2015-06-17', '19:30', ' Jl. Mawar IX Blok D6 No 9 ', 'Pnt. S.B. Harahap'),
(8, ' Ibadah Keluarga Sektor4b:Kel.E.Halauwet', '2015-06-17', '19:30', ' Jl. Ceria IV/17 Kp.Cerewed ', 'Dkn Ny. N. Rondonuwu'),
(9, ' Ibadah Keluarga Sektor5a:Kel.Ny.J.Risakotta', '2015-06-17', '19:30', '  Jl.Anggrek No 72 Cerewed ', 'Dkn T. Pangaribuan'),
(10, ' Ibadah Keluarga Sektor5b:Kel. Ny.E. M. Tehupeiory', '2015-06-17', '19:30', ' Jl.K.Timur B No 78 Blok A4 ', 'Pnt. J. Suripatty  '),
(11, ' Ibadah Keluarga Sektor6a:Kel. Rocky Noya', '2015-06-17', '19:30', ' Villa Setia Mekar Blok B2/16 Dkn ', 'Ny. Y. Tumengkol'),
(12, ' Ibadah Keluarga Sektor6b:Kel.F.Tuanakotta', '2015-06-17', '19:30', ' Pratama Residence Blok B/18 ', 'Pnt. Frans Dharmono'),
(13, ' Ibadah Keluarga Sektor7:Kel. J.Hutapea', '2015-06-17', '19:30', ' Jl.Prambanan Raya C6/15    ', 'Dkn Ny. F. Matulapelwa'),
(14, ' Ibadah Keluarga Sektor8:Kel. Ny.C.Balehendrik', '2015-06-17', '19:30', ' Jl. Cemara Baru I Raya No. 31    ', 'Pnt. Hendrik Natan'),
(15, ' Ibadah Keluarga Sektor9:Kel. T.H.Sibarani', '2015-06-17', '19:30', ' Jl. Mawar II Blok M5 No 11 ', 'Pnt.N.L. Rorimpandey'),
(16, ' Persiapan Ibadah Minggu Matius 13 : 24 - 30  Pembukaan', '2015-06-18', '19:00', ' Gedung Gereja ', 'Pnt. Rudy Kalumata'),
(17, ' Persiapan Ibadah Keluarga Galatia 6 : 1 - 10', '2015-06-18', '19:00', ' Ruang Petrus ', 'Pdt. Ny. M.Silahooij M.Pd.K'),
(18, ' Persiapan Ibadah Pelkat PKP Yohanes 15 : 6-8', '2015-06-18', '19:00', ' Ruang Daud ', 'Dkn Tonny Pangaribuan'),
(19, ' Persiapan Ibadah Pelkat PKB Roma 7 : 7 - 12', '2015-06-18', '19:00', ' Ruang Debora ', 'Pnt. N.L. Rorimpandey'),
(20, ' Persiapan Ibadah Pelkat GP 2 Korintus 8 : 1 - 5', '2015-06-18', '19:00', ' Ruang Paulus ', 'Pnt. Ny. M. Titarsole'),
(21, ' Persiapan Operator Projektor', '2015-06-18', '19:30', ' Ruang Operator (Balkon)  ', 'Sdr. Yugo Suharno'),
(22, ' Rapat PHMJ', '2015-06-18', '21:00', ' Ruang Paulus', ''),
(23, ' Latihan PS. PKP', '2015-06-19', '14:00', 'Gedung Gereja', ''),
(24, ' Ibadah Pelkat PKB Sektor1:Bpk O.Purba', '2015-06-19', '20:00', ' Perum BKP Blok DD No 3 ', 'Bpk Agus Sutarno'),
(25, ' Ibadah Pelkat PKB Sektor2:Bpk W.Saiya', '2015-06-19', '20:00', ' Jl. Mawar II Blok B No 32 ', 'Bpk Victor Rompis'),
(26, ' Ibadah Pelkat PKB Sektor 3 : Bpk Franca Wenas', '2015-06-19', '20:00', ' Jl.Bekasi Permai AF 4 No 4 ', 'Dkn'),
(27, ' Ibadah Pelkat PKB Sektor8:Bpk E.Matiho', '2015-06-19', '20:00', ' Jl.Cendrawasih 3 / 72 ', 'Bpk H. Hasibuan'),
(28, ' Ibadah Pelkat PKB Sektor9:Bpk R. Pakpahan', '2015-06-19', '20:00', ' Jl. Angsana II Blok D 2 No 13 ', 'Bpk Y.E.M.Masiki'),
(29, 'PS GP', '2015-06-19', '20:00', 'Gedung Gereja', 'Pdt');

-- --------------------------------------------------------

--
-- Table structure for table `tbl_nikah`
--

DROP TABLE IF EXISTS `tbl_nikah`;
CREATE TABLE IF NOT EXISTS `tbl_nikah` (
`id` int(11) NOT NULL,
  `suami` int(11) NOT NULL,
  `istri` int(11) NOT NULL,
  `tempat` varchar(255) NOT NULL,
  `tanggal` date NOT NULL DEFAULT '0000-00-00',
  `sipil` date NOT NULL DEFAULT '0000-00-00'
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=latin1;

--
-- Dumping data for table `tbl_nikah`
--

INSERT INTO `tbl_nikah` (`id`, `suami`, `istri`, `tempat`, `tanggal`, `sipil`) VALUES
(1, 1, 2, '', '2011-11-17', '2011-11-17'),
(5, 4, 5, 'Pekanbaru', '1999-08-21', '1999-08-21'),
(6, 17, 18, 'Pekanbaru', '1999-10-10', '2001-10-30'),
(7, 96, 97, '', '1990-09-27', '2007-11-29'),
(8, 67, 68, '', '1963-06-03', '0000-00-00');

-- --------------------------------------------------------

--
-- Table structure for table `tbl_page`
--

DROP TABLE IF EXISTS `tbl_page`;
CREATE TABLE IF NOT EXISTS `tbl_page` (
`id` int(9) unsigned NOT NULL,
  `parent_id` int(9) unsigned NOT NULL,
  `title` varchar(128) NOT NULL,
  `target` enum('#','page','category') NOT NULL,
  `menu_title` varchar(128) NOT NULL,
  `content` longtext NOT NULL,
  `sequence` int(11) NOT NULL DEFAULT '0',
  `seo_title` text NOT NULL,
  `meta` text NOT NULL,
  `url` varchar(255) NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8;

--
-- Dumping data for table `tbl_page`
--

INSERT INTO `tbl_page` (`id`, `parent_id`, `title`, `target`, `menu_title`, `content`, `sequence`, `seo_title`, `meta`, `url`) VALUES
(1, 0, 'Tentang Kami', 'page', 'tentang-kami', '', 0, '', '', ''),
(2, 1, 'Visi Misi', 'page', 'visi-misi', '<h2 style=\\"font-style:italic;\\">VISI GPIB</h2>\\r\\n\\r\\n<p>&#39;GPIB menjadi gereja yang mewujudkan damai sejahtera bagi seluruh ciptaanNya&#39;</p>\\r\\n\\r\\n<p>&nbsp;</p>\\r\\n\\r\\n<h2 style=\\"font-style:italic;\\">MISI GPIB</h2>\\r\\n\\r\\n<p>Menempatkan Tuhan Yesus Kristus, Juru Selamat manusia sebagai Kepala Gereja.&nbsp;</p>\\r\\n\\r\\n<p>Mewujudkan kehadiran GPIB yang membawa corak damai sejahtera Allah dan menjadi berkat di tengah - tengah masyarakat dan dunia.&nbsp;</p>\\r\\n\\r\\n<p>Membangun suatu Jemaat Misioner yang bertumbuh, dewasa dalam iman. Kehidupannya adalah teladan serta memberi kontribusi nyata bagi kemajuan gereja, masyarakat dan bangsa Indonesia dalam suatu semangat oikumenis dan Nasional.</p>\\r\\n\\r\\n<p>&nbsp;</p>\\r\\n\\r\\n<h2 style=\\"font-style:italic;\\">MOTO GPIB&nbsp;</h2>\\r\\n\\r\\n<p>&#39;Dan orang akan datang dari timur dan barat dan dari utara dan selatan dan mereka duduk makan di dalam Kerajaan Allah&#39;. (Lukas 13 : 29)</p>\\r\\n', 0, '', '', 'page/visi-misi'),
(3, 1, 'Sejarah', 'category', '4', '', 0, '', '', 'category/4'),
(4, 1, 'Pemahaman Iman GPIB', 'page', '', '<h2 style=\\"font-style:italic;\\">I KESELAMATAN</h2>\\r\\n\\r\\n<p>KAMI MENGAKU,&nbsp;</p>\\r\\n\\r\\n<ol>\\r\\n	<li>Bahwa Allah yang esa 1) dengan FirmanNya dalam kasihNya yang tiada tara telah memulai karya keselamatan bagi 2) alam semesta 3) sejak awal Penciptaan 4) dan setelah kejatuhan manusia dalam dosa 5). Allah meneruskan karyaNya untuk memelihara alam semesta dari derita dan maut 6). Karya keselamatan ini berlangsung sampai pada akhir zaman 7).&nbsp;</li>\\r\\n	<li>Bahwa Yesus Kristus 1) telah mati, bangkit dan naik ke surga 2) menjamin keselamatan orang percaya dan membeba-skannya dari kuasa dosa 3), derita dan maut 4). Dengan demikian relasi manusia dengan Allah dan relasi manusia dengan sesama ciptaan-Nya telah dipulihkan. Hal itu akan senantiasa kami peringati melalui sakramen: Baptisan 5) dan Perjamuan 6).&nbsp;</li>\\r\\n	<li>Bahwa dalam 1) karya keselamatan iAllah telah memanggil 2) Abraham 3) menjadi umat Perjanjian Lama, juga Israel dari perhambaan di Mesir dan menyelamatkannya 4) dari kepunahan. Allah meneruskan 5) kasih setiaNya de-ngan melindungi dan menuntun umatNya kembali yang terserak dan tercerai berai di tanah pembuangan 6)&nbsp;</li>\\r\\n	<li>Bahwa dalam karya keselamatan melalui Yesus Kristus, Allah telah menyelamatkan dan menghimpun 1) umat Perjanjian Baru 2) yaitu Gereja 3) yang diutus-Nya untuk memberitakan Injil 4) dan menghadirkan tanda-tanda kerajaan Allah 5) di atas bumi.&nbsp;</li>\\r\\n	<li>Bahwa oleh kasihNya yang tiada tara 1), Allah telah mewujud nyatakan keselamatan itu sepenuhnya melalui pekerjaan Yesus Kristus 2). Supaya setiap orang yang percaya kepadaNya tidak binasa melainkan memperoleh hidup yang kekal 3).&nbsp;</li>\\r\\n	<li>Bahwa Yesus Kristus yang adalah Raja 1) dari segala raja dan Tuan dari segala tuan 2) akan menyatakan kepenuhan Keselamatan 3) pada saat Ia datang kembali kelak sebagai Hakim 4) dan Raja yang duduk disebelah kanan Allah Bapa yang Maha Kuasa.5)&nbsp;</li>\\r\\n	<li>Bahwa keselamatan yang dikerjakan Kristus terbuka bagi seluruh umat yang ada di muka bumi yang terdiri dari berbagai suku- bangsa. Dalam kasih-Nya yang tiada tara Allah mengaruniakan keselamatan, yakni: kemer-dekaan 1) kepada bangsa Indonesia. Sebagai bangsa yang dimerdekakan bertanggung jawab mengupayakan pembebasan dari ketidak adilan 2), perusakan alam 3) dan pelecehan hak asasi manusia 4), kemerosotan etis-moral 5) dan bentuk penindasan lainnya.&nbsp;</li>\\r\\n	<li>Bahwa melalui Roh Kudus, Allah menuntun 1) orang percaya mengakui 2) Yesus Kristus selaku Tuhan dan Juruslamat 3) dalam pergumulannya di dunia.&nbsp;</li>\\r\\n</ol>\\r\\n\\r\\n<h2 style=\\"font-style:italic;\\">II - GEREJA</h2>\\r\\n\\r\\n<ol>\\r\\n	<li>Bahwa Allah Bapa telah memanggil dan menghimpun 1) dari antara bangsa - bangsa suatu umat 2) bagi Diri-Nya untuk menjadi berkat 3).&nbsp;</li>\\r\\n	<li>Bahwa panggilan itu dilanjutkan melalui Anak-Nya, yaitu Yesus yang adalah Tuhan 1). Dialah yang memanggil dan menjadi dasar 2) terbentuknya umat yang baru, yaitu Gereja 3).&nbsp;</li>\\r\\n	<li>Bahwa sepanjang sejarah dan di manapun di dunia, dari utara, selatan, barat dan timur, 1) orang-orang percaya dipanggil dan dituntun oleh Roh Kudus 2) untuk menjadi satu persekutuan 3) yang menjalankan tugas pelayanan, dan kesaksian 4).&nbsp;</li>\\r\\n	<li>Bahwa Yesus Kristus adalah Kepala Gereja 1) dan Gereja sebagai tubuh-Nya 2) yang rapi tersusun 3), dan segala sesuatu di dalamnya harus diselenggarakan secara tertib dan teratur 4).&nbsp;</li>\\r\\n	<li>Bahwa Gereja terpanggil untuk senantiasa menyata-kan keesaannya 1), supaya dunia percaya bahwa Allah Bapa telah mengutus Yesus Kristus 2), untuk menjalankan karya keselamatan bagi dunia 3) ini.&nbsp;</li>\\r\\n	<li>Bahwa keberadaan Gereja sebagai umat Allah terus menerus mengalami pembaharuan 1) bersama dan dengan seluruh ciptaan menyongsong penggenapan pemerintahan Allah .</li>\\r\\n	<li>Bahwa kendatipun Gereja terpanggil menghadirkan tanda-tanda Pemerintahan Allah 1), tetapi Gereja bukan Pemerintahan Allah itu sendiri 2).&nbsp;</li>\\r\\n	<li>Bahwa Gereja Protestan di Indonesia bagian Barat 1) bersama Gereja-Gereja lain adalah perwujudan dari Gereja Yesus Kristus 2) yang esa , kudus , am dan rasuli 3) yang berada dan berkarya di Indonesia yang beragam.&nbsp;</li>\\r\\n	<li>Bahwa Tuhan yang memanggil dan menetapkan para pelayan-Nya 1) sebagai Presbiter 2) yang berjalan bersama-sama 3) untuk memperlengkapi warga 4) GPIB yang missioner 5) sebagai manusia yang utuh.&nbsp;</li>\\r\\n</ol>\\r\\n\\r\\n<h2 style=\\"font-style:italic;\\">III - MANUSIA&nbsp;</h2>\\r\\n\\r\\n<ol>\\r\\n	<li>Bahwa manusia 1): laki dan perempuan 2), diciptakan sepadan 3) oleh Allah menurut rupa dan gambar-Nya 4).&nbsp;</li>\\r\\n	<li>Bahwa manusia diciptakan Allah sebagai mahluk religius 1) dan makhluk sosial 2) yang diberikan kemampuan 3) untuk membangun relasi secara positif dengan sesamanya demi kebersamaan dan kesejahteraan seluruh ciptaan-Nya.&nbsp;</li>\\r\\n	<li>Bahwa manusia laki-laki dan perempuan disatukan dalam pernikahan 1) untuk saling mengasihi dan melengkapi 4).&nbsp;</li>\\r\\n	<li>Bahwa manusia bertanggung-jawab untuk bekerja 1) dalam rangka memelihara dan melestarikan, 2) alam. Untuk menunaikan tugas yang mulia ini manusia maupun struktur masyarakatnya tidak boleh disanjung dan dipuja 3).&nbsp;</li>\\r\\n	<li>Bahwa manusia diberi kemampuan dan wewenang menata-layani alam 1) berserta isinya; kemampuan dan wewenang ini dilaksanakannnya dalam keseimbangan di antara kebebasan dan tanggung-jawab 2), dan di antara hak dan kewajiban 3).&nbsp;</li>\\r\\n	<li>Bahwa karena keinginannya manusia 1) menyalahgunakan kuasa 2) dan tanggung-jawabnya, sehingga ia jatuh dalam dosa 3) menyebabkan rusaknya hubungan 4) dengan Allah, sesama dan alam.&nbsp;</li>\\r\\n	<li>Bahwa manusia memerlukan anugerah pembaruan 1), agar dapat melanjutkan pekerjaanNya hingga pemenuhan kerajaan Allah 2).&nbsp;</li>\\r\\n	<li>Bahwa hanya oleh kemurahan Allah 1) melalui Yesus Kristus dan di dalam persekutuan 2) dengan Roh Kudus, martabat manusia sebagai gambar Allah 3) dipulihkan kembali, sehingga ia dapat menghayati dan menikmati hidup kekal 4) dalam kehidupan yang sekarang ini maupun dalam kehidupan yang akan datang.&nbsp;</li>\\r\\n</ol>\\r\\n\\r\\n<h2 style=\\"font-style:italic;\\">IV - ALAM DAN SUMBER DAYA&nbsp;</h2>\\r\\n\\r\\n<ol>\\r\\n	<li>Bahwa Allah menciptakan alam dan sumber daya-nya 1). Allah mempercayakan pengelolaannya kepada negara 2) dengan penuh tanggung jawab 3) demi kesejahteraan 4) manusia dan kelangsungan hidup sesama ciptaanNya.&nbsp;</li>\\r\\n	<li>Bahwa kekuatan-kekuatan alam 1) yang kelihatan dan yang tidak kelihatan, takluk pada kuasa Allah dan karena itu alam tidak boleh disembah 2).&nbsp;</li>\\r\\n	<li>Bahwa alam dan sumber dayanya telah dipulihkan oleh Yesus Kristus 1). Karena itu manusia yang telah didamaikan dan dipulihkan, wajib memelihara alam dan sumber dayanya dengan penuh perhatian dan rasa tanggung jawab&nbsp;</li>\\r\\n	<li>Bahwa dengan ilmu pengetahuan dan teknologi 1), manusia boleh meneliti dan mengelola alam beserta sumber dayanya, secara tepat guna sehingga alam memiliki kesempatan untuk memperbaharui dirinya dan berdaur ulang 2).&nbsp;</li>\\r\\n	<li>Bahwa oleh karena kuasa dosa, manusia cenderung untuk menguasai alam bagi kepentingan dan keuntungan pribadi, sehingga terjadi benturan kepentingan yang mengakibatkan dampak kerusakan alam. Hanya oleh pendamaian antara Allah dan manusia yang dilaksanakan dengan perantaraan Tuhan Yesus Kristus, maka manusia sebagai ciptaan baru 1) dapat melihat kembali pentingnya alam sebagai rumah dan sarana kehidupan bagi segala mahluk.&nbsp;</li>\\r\\n	<li>Bahwa karena pembaruan Roh Kudus 1), Gereja memiliki kewajiban moral 2) untuk bersama-sama pemerintah dan bangsa-bangsa berusaha menata ekologi dan mencegah pengrusakan alam.&nbsp;</li>\\r\\n</ol>\\r\\n\\r\\n<h2 style=\\"font-style:italic;\\">V - NEGARA DAN BANGSA&nbsp;</h2>\\r\\n\\r\\n<ol>\\r\\n	<li>Bahwa Allah, sebagai Sumber Kuasa, memberikan kuasa kepada pemerintah bangsa-bangsa guna mendatang-kan keadilan dan kesejahteraan, memelihara ketertib-an serta mencegah dan meniadakan kekacauan dan kejahatan 1).Dengan demikian sebagai hamba Allah 2), setiap pemerintah wajib mempertanggung jawabkan kuasa tersebut kepada Allah.&nbsp;</li>\\r\\n	<li>Bahwa pemerintah dan negara menjalankan kuasa dan wewenang di bawah terang Tuhan Yesus Kristus, yang berfirman: &quot;berilah kepada kaisar apa yang kaisar punya dan kepada Allah apa yang Allah punya&quot; 1) Dengan demikian pemerintah dan negara mempunyai otonomi 2), tetapi otonomi ini tidak dapat mengatasi otonomi Gereja sebagai tubuh Kristus. Oleh karena kaisar berada di bawah Allah.&nbsp;</li>\\r\\n	<li>Bahwa kuasa yang diberikan kepada pemerintah itu dapat disalahgunakan karena dijadikan sebagai tujuan, hingga timbul kelaliman, kejahatan dan keresahan 1). Jika terjadi demikian maka sebagai Hakim dan Raja 2) Tuhan Yesus Kristus yang duduk di sebelah kanan Allah 3) akan menghakimi pemerintah pemerintah dan penguasa 4).&nbsp;</li>\\r\\n	<li>Bahwa Roh Kudus yang adalah Roh keberanian akan menolong orang percaya untuk lebih taat kepada Allah dari pada kepada manusia 1). Seperti yang telah disaksikan oleh para Rasul ; oleh karena itu Gereja terpanggil memper-dengarkan suara kenabian 2) terhadap masalah negara, bangsa, dan masyarakat.&nbsp;</li>\\r\\n	<li>Bahwa berdasarkan tuntunan Roh Kudus, warga jemaat yang adalah sekaligus warga negara wajib menaati undang-undang dan penjabarannya yang telah menjadi ketetapan bersama 1), namun ia wajib memberi saran-saran perbaikan secara kritis dan konstruktif lewat saluran saluran pengawasan demi keadilan dan kesejahteraan bangsa.2)&nbsp;</li>\\r\\n	<li>Bahwa berdasarkan tuntunan Roh Kudus, warga jemaat yang adalah sekaligus warga negara 1) perlu membina rasa kebersamaan sebagai satu bangsa 2) yaitu Indonesia, membangun saling pengertian dan toleransi dalam rangka menghayati kerukunan 3) nasional, dan meng-galang kemajuan bersama 4) bagi rakyat Indonesia.&nbsp;</li>\\r\\n	<li>Bahwa berdasarkan tuntunan Roh Kudus, warga jemaat yang adalah sekaligus warga negara, di dalam kehidupan bernegara, berbangsa, dan bermasyarakat, perlu mem-bangun rasa persatuan dan kesatuan 1) yang tidak merusak kebhinekaan dan kesetaraan 2) yang telah menjadi bagian dari masyarakat warga ( civil -society ), di mana hak - hak asasi manusia dijunjung tinggi 3).&nbsp;</li>\\r\\n</ol>\\r\\n\\r\\n<h2 style=\\"font-style:italic;\\">VI - MASADEPAN&nbsp;</h2>\\r\\n\\r\\n<ol>\\r\\n	<li>Bahwa Allah dalam karya penyelamatan dan penciptaanNya menghantar orang percaya dari satu titik sejarah ke titik sejarah yang baru sehingga masa depan senantiasa tercakup dalam apa yang dibuatnya pada masa kini dan masa lalu 1).&nbsp;</li>\\r\\n	<li>Bahwa kedatangan Yesus Kristus sebagai Tuhan dan Juruselamat ke dalam dunia mem-berikan jaminan dan harapan yang pasti bagi orang yang percaya.&nbsp;</li>\\r\\n	<li>Bahwa Yesus Kristus adalah Tuhan 1) yang menjadi pusat ibadah 2) dan harapan 3) manusia dari zaman ke zaman dan Dia juga harapan mahluk lainnya,4) karena Dia-lah yang akan mendatangkan langit baru dan bumi baru 5) dimana derita dan maut tidak akan ada lagi tanpa Dia dunia tidak memiliki pengharapan 6)&nbsp;</li>\\r\\n	<li>Bahwa kebangkitan Yesus Kristus 1) maka orang percaya akan dibangkitkan dari kemati-an 2) dan dikumpulkan bersama-sama Dia 3) dalam keadaan yang Mulia 4). Oleh sebab itu maut bukanlah kata akhir dalam segala sesuatu melainkan hidup dalam kuasa kasih Yesus 5)&nbsp;</li>\\r\\n	<li>Bahwa Roh Kudus adalah roh pengharapan, akan menolong orang percaya untuk tetap berpaut pada kasih Kristus dan tidak ada suatu kuasa apapun yang dapat memisahkan orang percaya dari kasih Kristus 1). Apa yang dijanjikan kepada orang percaya untuk masa depan sudah mulai dialami pada masa kini 2), oleh karena sekarangpun orang percaya sudah hidup di dalam pengharapan 3)&nbsp;</li>\\r\\n	<li>Bahwa Roh Kudus yang adalah Roh masa depan menyadarkan orang percaya pada panggilan-Nya menjaga keutuhan dari bangsa dan negara 1) untuk mengisi kurun waktu menjelang masadepan yang pasti 2) itu dengan sikap, tindakan dan karya yang menghadirkan keadilan dan kebenaran berdasarkan kasih serta pemulihan 3) pemenuhan janji Allah akan langit baru dan bumi baru.&nbsp;</li>\\r\\n</ol>\\r\\n\\r\\n<h2 style=\\"font-style:italic;\\">VII - FIRMAN ALLAH&nbsp;</h2>\\r\\n\\r\\n<ol>\\r\\n	<li>Bahwa dengan perantaraan firman-Nya 1) Allah telah mencip-takan 2) langit dan bumi serta isinya. Firman Allah berkuasa 3) untuk mengubah dan membaharui. 4).&nbsp;</li>\\r\\n	<li>Bahwa Firman Allah telah menjadi manusia 1) di dalam dan melalui Yesus Kristus.&nbsp;</li>\\r\\n	<li>Bahwa dengan terang Roh Kudus, persekutuan orang percaya menetapkan tulisan-tulisan 1) yang memberitakan per-buatan Allah serta respon manusia terhadap tindakan Allah pada kurun waktu tertentu.&nbsp;</li>\\r\\n	<li>Bahwa dengan tuntunan Roh Kudus para penulis Alkitab menceritakan dan memberitakan perbuatan-perbuatan besar Allah dalam bentuk tulisan pada suatu kurun waktu tertentu dan juga respons manusia terhadap tindakan-tindakan Allah pada kurun waktu tertentu 3)</li>\\r\\n</ol>\\r\\n', 0, '', '', '#');

-- --------------------------------------------------------

--
-- Table structure for table `tbl_sbu`
--

DROP TABLE IF EXISTS `tbl_sbu`;
CREATE TABLE IF NOT EXISTS `tbl_sbu` (
`id` int(11) NOT NULL,
  `kategori` enum('pagi','malam') NOT NULL,
  `tanggal` date NOT NULL DEFAULT '0000-00-00',
  `nats` varchar(255) NOT NULL,
  `nyanyian` varchar(255) NOT NULL,
  `judul` varchar(255) NOT NULL,
  `desk` text NOT NULL,
  `create_by` int(11) NOT NULL,
  `update_by` int(11) NOT NULL,
  `last_update` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;

--
-- Dumping data for table `tbl_sbu`
--

INSERT INTO `tbl_sbu` (`id`, `kategori`, `tanggal`, `nats`, `nyanyian`, `judul`, `desk`, `create_by`, `update_by`, `last_update`) VALUES
(1, 'pagi', '2015-06-18', 'Galatia 2:11-14', 'KJ.425 : 1 - Berdoa', 'SIAP KOMPROMI', '<p>Galatia 2:11-14<br />\r\nTetapi waktu Kefas datang ke Antiokhia, aku berterang-terang menentangnya, sebab ia salah (ay.11)<br />\r\n<br />\r\nSetiap daerah pasti memiliki budaya kerja, budaya pergaulan serta tradisi hidup masing-masing. Orang akan dianggap aneh bahkan akan ditegur jika berbuat sesuatu yang tidak lazim dan berbeda dengan budaya setempat yang ada. Orang baru yang memasuki budaya yang sama sekali baru awalnya pasti merasa aneh. Tetapi, lam bat laun ia akan berkompromi dengan lingkungannya. Masalahnya, bagaimana jika budaya itu tidak sesuai dengan Firman Allahy?<br />\r\n<br />\r\nHal ini dialami oleh Petrus. Dia adalah rasul yang pertama kali memberitakan keselamatan bagi orang non Yahudi. Apa yang dilakukan Petrus da|_am mendobrak tradisi pelayanan yang ada saat itu. Sebelumnya, Petrus pun sempat menjadi takut menjadi pribadi yang berbeda. la sempat takut dengan pandangan miring murid-murid Yakobus karena makan dengan orang-orang non Yahudi. Di dunia kerja, seharusnya kita bisa menjad sosok yang berani mendobrak budaya kerja yang kaku, kurang humanis, tidak produktif dan curang.<br />\r\n<br />\r\nMenjadi berbeda memang tidak mudah. Namun bukan berarti kita harus kompromi terus-menerus dengan budaya negatif yang ada di sekitar kita. lkutilah budaya setempat selama budaya itu tidak melanggar prinsip firman Tuhan, tapi beranikan diri untuk menjadi? sosok perubahan untuk mengubah budaya negatif.<br />\r\n<br />\r\nKJ. 425 V: 3<br />\r\nDoa : (Mampukan kaml, untuk kami tidak berkompromi dengan hal-hal yang tidak sesuai dengan ?rman-Mu, ya Tuhan)</p>\r\n', 3, 0, '2015-06-18 03:46:47'),
(2, 'malam', '2015-06-18', 'Galatia 2:15-21', 'KJ.419:1 -Berdoa', 'BERIMAN SECARA DEWASA', '<p>Galatia 2:15-21<br />\r\nNamun aku hidup, tetapi bukan lagi aku sendiri yang hidup. melainkan Kristus yang hidup di dalam aku (ay.20a)<br />\r\n<br />\r\nIman itu dinamis. lman dapat mati dan gugur. Tapi juga bisa hidup, bertumbuh dan berkembang. Ketika Alkitab berbicara tentang iman, maka iman dikelompokan menjadi 2 bagian. Pertama, iman yang kekanak-kanakan dan kedua iman yang dewasa. lman yang-kekanak-kanakan adalah iman yang egosentris. Berpusat pada diri sendiri. Selalu berpamrih, bersyarat dan penuh dengan tuntutan. Sebaliknya, lman yang dewasa adalah iman mampu mencintai Tuhan apa adanya. Iman yang dewasa adalah iman yang dapat menerima bukan hanya yang baik saja dari Allah, tetapi juga yang buruk. lman yang dewasa bertolak dari hati yang mengasihi tanpa syarat, tidak berpamrih, dan tidak menuntut.<br />\r\n<br />\r\nlman yang dewasa adalah iman yang dapat mengatakan seperti Paulus, &quot;Hidupku bukan aku lagi, tetapi Kristus yang hidup di dalam aku.&quot; Separti itulah makna beriman, seperti Paulus yang tahu apa arti tujuan hidupnya. Mengenal dengan jelas siapa yang menjadi pusat dalam hidupnya. lman memungkinkan Paulus melihat dan memandang kehidupan dan sanggup menemukan keindahan kehidupan, pun di tengah kesuraman. Dengan iman Paulus dapat memaknai hidupnya, bahkan hidupnya pun menjadi lebih bermakna, karena Kristus juga hidup dalam dirinya.<br />\r\n<br />\r\nMarilah kita belajar untuk beriman secara dewasa. Kita bisa memulainya dari hal-hal yang sederhana dan sehari-hari. Betul, bahwa hal itu tidak mudah. Ada risikonya. Tetapi jangan sampai kenyataan itu membuat langkah kita surut.<br />\r\n<br />\r\nKJ. 419 : 2<br />\r\nDoa : (Berikanlah kami iman yang teguh, ya Tuhan. Mampukanlah kami senantiasa menghadirkan Kristus dalam hidup, kerja dan layan kami)</p>\r\n', 3, 0, '2015-06-18 03:50:14');

-- --------------------------------------------------------

--
-- Table structure for table `tbl_slider`
--

DROP TABLE IF EXISTS `tbl_slider`;
CREATE TABLE IF NOT EXISTS `tbl_slider` (
`slider_id` int(5) NOT NULL,
  `slider_path` varchar(180) NOT NULL,
  `slider_title` varchar(80) NOT NULL,
  `slider_caption` varchar(120) NOT NULL,
  `slider_img` varchar(255) NOT NULL,
  `created_at` datetime NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=latin1;

--
-- Dumping data for table `tbl_slider`
--

INSERT INTO `tbl_slider` (`slider_id`, `slider_path`, `slider_title`, `slider_caption`, `slider_img`, `created_at`) VALUES
(5, 'Slider', 'Hadapi Semua Dengan Senyuman', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry''s standard ', '603074_10200797453925873_1917385995_n_wide.jpg', '2015-06-17 07:45:05'),
(6, 'Slider', ' Bagi Tuhan Tak ada yang mustahil', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry''s standard ', 'ciputranews_1360028588.jpg', '2015-06-17 07:46:12');

-- --------------------------------------------------------

--
-- Table structure for table `tbl_users`
--

DROP TABLE IF EXISTS `tbl_users`;
CREATE TABLE IF NOT EXISTS `tbl_users` (
`id` int(11) unsigned NOT NULL,
  `username` varchar(255) NOT NULL DEFAULT '',
  `email` varchar(255) NOT NULL DEFAULT '',
  `password` varchar(255) NOT NULL DEFAULT '',
  `fullname` varchar(255) NOT NULL,
  `avatar` varchar(255) DEFAULT 'default.jpg',
  `created_at` datetime NOT NULL,
  `updated_at` datetime DEFAULT NULL,
  `is_admin` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `is_confirmed` tinyint(1) unsigned NOT NULL DEFAULT '0'
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1;

--
-- Dumping data for table `tbl_users`
--

INSERT INTO `tbl_users` (`id`, `username`, `email`, `password`, `fullname`, `avatar`, `created_at`, `updated_at`, `is_admin`, `is_confirmed`) VALUES
(1, 'samson', 'samson@sinaga.or.id', '$2y$10$Nf4j/5ptH2EYAxvDzr0iNODQbDP3OqRE2hPJ/RucyYCY5LUbIkOJG', 'Samson Sinaga', 'default.jpg', '2015-06-05 03:29:45', NULL, 1, 1),
(2, 'victor', 'victorsiahaan03@gmail.com', '$2y$10$RtRdVt1krlAg4LzZITEbEuydto1iUIsuug0gJzkp9tymz0DPIbx72', 'Victor Siahaan', 'default.jpg', '2015-06-11 09:17:28', NULL, 0, 0),
(3, 'admin', 'me@home.net', '$2y$10$sYHxetsCWr6W0hyRh1aaxeQoDC39O3IrcEwvxdGVhQEBz/3R7wjBm', 'Admin GPIB', 'default.jpg', '2015-06-11 09:32:16', NULL, 1, 1);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `ci_sessions`
--
ALTER TABLE `ci_sessions`
 ADD PRIMARY KEY (`id`), ADD KEY `ci_sessions_timestamp` (`timestamp`);

--
-- Indexes for table `tbl_berita`
--
ALTER TABLE `tbl_berita`
 ADD PRIMARY KEY (`id`), ADD UNIQUE KEY `slug` (`slug`);

--
-- Indexes for table `tbl_category`
--
ALTER TABLE `tbl_category`
 ADD PRIMARY KEY (`id`), ADD UNIQUE KEY `slug` (`slug`);

--
-- Indexes for table `tbl_jemaat`
--
ALTER TABLE `tbl_jemaat`
 ADD PRIMARY KEY (`id`);

--
-- Indexes for table `tbl_kegiatan`
--
ALTER TABLE `tbl_kegiatan`
 ADD PRIMARY KEY (`id`);

--
-- Indexes for table `tbl_nikah`
--
ALTER TABLE `tbl_nikah`
 ADD PRIMARY KEY (`id`), ADD UNIQUE KEY `suami` (`suami`), ADD UNIQUE KEY `istri` (`istri`);

--
-- Indexes for table `tbl_page`
--
ALTER TABLE `tbl_page`
 ADD PRIMARY KEY (`id`);

--
-- Indexes for table `tbl_sbu`
--
ALTER TABLE `tbl_sbu`
 ADD PRIMARY KEY (`id`);

--
-- Indexes for table `tbl_slider`
--
ALTER TABLE `tbl_slider`
 ADD PRIMARY KEY (`slider_id`);

--
-- Indexes for table `tbl_users`
--
ALTER TABLE `tbl_users`
 ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `tbl_berita`
--
ALTER TABLE `tbl_berita`
MODIFY `id` int(11) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=21;
--
-- AUTO_INCREMENT for table `tbl_category`
--
ALTER TABLE `tbl_category`
MODIFY `id` int(11) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=18;
--
-- AUTO_INCREMENT for table `tbl_jemaat`
--
ALTER TABLE `tbl_jemaat`
MODIFY `id` int(11) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=168;
--
-- AUTO_INCREMENT for table `tbl_kegiatan`
--
ALTER TABLE `tbl_kegiatan`
MODIFY `id` int(11) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=30;
--
-- AUTO_INCREMENT for table `tbl_nikah`
--
ALTER TABLE `tbl_nikah`
MODIFY `id` int(11) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=9;
--
-- AUTO_INCREMENT for table `tbl_page`
--
ALTER TABLE `tbl_page`
MODIFY `id` int(9) unsigned NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=5;
--
-- AUTO_INCREMENT for table `tbl_sbu`
--
ALTER TABLE `tbl_sbu`
MODIFY `id` int(11) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=3;
--
-- AUTO_INCREMENT for table `tbl_slider`
--
ALTER TABLE `tbl_slider`
MODIFY `slider_id` int(5) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=7;
--
-- AUTO_INCREMENT for table `tbl_users`
--
ALTER TABLE `tbl_users`
MODIFY `id` int(11) unsigned NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=4;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
